### ISSUE TITLE
Can't save the colorscheme when change it from Dashboard

### ISSUE THREAD

**Issue by p1k0pan** [glepnir/dashboard-nvim#100]
I can change colorscheme on dashboard successfully, but it doesn't show it next time and it shows the colorscheme befor I changed. 

How can I change it from dashboard and meanwhile save it to the settings?

By the way I set colorscheme `vim.cmd [[colorscheme zephyr]]` and run.

**Comment by rebelot** [comment]
in your config, the colorscheme must be set first, then you can override hlgroups like this:
```lua
vim.cmd [[colorscheme zephyr]]
vim.cmd("hi! link DashboardHeader Error")
```

**Comment by fedusiv** [comment]
I have same issue on neovim. Do not understand how to solve this issue. Can you please help me?

**Comment by p1k0pan** [comment]
> I have same issue on neovim. Do not understand how to solve this issue. Can you please help me?

don't know yet, now I just not changing colorscheme on dashboard. Change it from setting

**Comment by fedusiv** [comment]
> > I have same issue on neovim. Do not understand how to solve this issue. Can you please help me?
> 
> don't know yet, now I just not changing colorscheme on dashboard. Change it from setting

I found issue. I used style of colorscheme. it should be set before setting colorscheme. Maybe it will help someone
let g:material_style = "deep ocean"
colorscheme material
