### ISSUE TITLE
Not an editor command: Clap marks

### ISSUE THREAD

**Issue by ricbermo** [glepnir/dashboard-nvim#103]
![image](https://user-images.githubusercontent.com/2601363/134178107-b7a8a7fa-33d8-4d19-9e35-209d90dcc6b8.png)

the config:

`g.dashboard_default_executive = "telescope"`

Hi there, I just wanted to report this issue.

I wasn't able to find something in the readme that would've helped me. Maybe I just missed it.

Thanks!!

**Comment by LollipopFt** [comment]
did you do
```lua
local g = vim.g
```
and write your config in a lua file?

**Comment by ricbermo** [comment]
@LollipopFt yes, I'm using [NVChad](https://github.com/NvChad/NvChad/blob/main/lua/plugins/configs/dashboard.lua)

**Comment by Clejd** [comment]
I had the same issue. I tried to put the same configuration in the init.vim file instead of dashboard.lua and it works fine for me.
