### ISSUE TITLE
The session "~/.cache/vim/session/vim_ plugged_dashboard-nvim_autoload_dashboard.vim" d oesn't exist

### ISSUE THREAD

**Issue by Ruixi-rebirth** [glepnir/dashboard-nvim#107]
当我使用 open last session时,报The session "/home/ruixi/.cache/vim/session/vim_
plugged_dashboard-nvim_autoload_dashboard.vim" d
oesn't exist错误,我看了看我确实没有这个文件甚至连vim文件夹都没有,我想是不是需要自己创建?

**Comment by dingZvel** [comment]
我也遇到了这个问题，我是win10系统，我估计你的也是windows系统
我怀疑问题出在你没有使用命令”:SessionSave“就直接使用"open last session"(这条命令其实等价于）“:SessionLoad"
而在Windows非管理员权限下有时可能你在当前目录没有完全控制权限，我怀疑是这一点导致无法使用":SessionSave"以保存一个Session，从而没法"open last session"

**Comment by dingZvel** [comment]
更新：使用[issuue#98](https://github.com/glepnir/dashboard-nvim/pull/98#issue-982427682)的改进代码解决了此问题

**Comment by Ruixi-rebirth** [comment]
Thank you!
