### ISSUE TITLE
how to reopen dashboard after close all buffers?

### ISSUE THREAD

**Issue by jrafaaael** [glepnir/dashboard-nvim#108]
Is there a way to reopen the dashboard by closing all buffers? By default, closing all buffers opens a new empty file

**Comment by Clejd** [comment]
`nnoremap <silent> <expr> <leader>d winnr('$')==1 && tabpagenr('$')==1 && (len(getbufinfo({'buflisted':1})))==1 ? ':bw<CR>:Dashboard<CR>' : ':bw<CR>'`
This works fine for me, i use <leader>d to close a buffer and if there is none it opens dashboard.

**Comment by Clejd** [comment]
`nnoremap <silent> <expr> <leader>d winnr('$')==1 && tabpagenr('$')==1 && (len(getbufinfo({'buflisted':1})))==1 ? ':bw<CR>:Dashboard<CR>' : ':bw<CR>'`
This works fine for me, i use d to close a buffer and if there is none it opens dashboard.
