### ISSUE TITLE
Making logos

### ISSUE THREAD

**Issue by bryant-the-coder** [glepnir/dashboard-nvim#110]
Hi, where can I make those logos? It looks interesting 🙃

**Comment by tuwuna** [comment]
Here you goes: https://www.twitchquotes.com/ascii-art-generator

Better late than never :D

**Comment by bryant-the-coder** [comment]
Do u know what happened to glepnir?

**Comment by tuwuna** [comment]
https://github.com/glepnir/lspsaga.nvim/pull/207#issuecomment-863150249

This is the last activity s/he on github :<

**Comment by bryant-the-coder** [comment]
9 mo ago?? I hope he is ok. Dashboard.nvim is a good plugin
