### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by uncomfyhalomacro** [glepnir/dashboard-nvim#124]
Glepnir has been AWOL for a while now, i wonder what is the status of this project, and are there any existing forks for this?

**Comment by SystematicError** [comment]
https://github.com/rockerBOO/awesome-neovim#startup
You can check this list for alternatives

**Comment by uncomfyhalomacro** [comment]
Hoping Glepnir is alive and well even if he cannot contribute again. closing.
