### ISSUE TITLE
custom

### ISSUE THREAD

**Issue by SongTianxian9** [glepnir/dashboard-nvim#127]
thanks for your work , I want know how can i change red line 
![image](https://user-images.githubusercontent.com/88336105/154440159-03de5d06-5d12-49f4-8f48-5f1db40ee12c.png)

**Comment by JorgeMorah** [comment]
let g:dashboard_custom_footer = [' '] <- For text
highlight dashboardFooter    guifg='#FFFFFF' <-For color

**Comment by SongTianxian9** [comment]
> For text `let g:dashboard_custom_footer = ['Hello']` For color `highlight dashboardFooter guifg='#FFFFFF' `

thank you!!
