### ISSUE TITLE
Is there an option to remove word and line count on the bottom of that last status bar

### ISSUE THREAD

**Issue by ghost** [glepnir/dashboard-nvim#131]
Hey there thanks for this plugin, i was just wondering if there's an option to remove those useless stuff on the picture they are kinda messing with the dashboard. i have added this to my config `vim.g.dashboard_disable_statusline = 1`  to hide `laststatus` but it doesn't hide line and word count, any help will be appreciated.

![github-issue](https://user-images.githubusercontent.com/100243267/161314965-24187504-9d05-4627-86bd-9d4d4f89b488.png)

**Comment by roginfarrer** [comment]
For anyone else that finds this, you can disable it with

```lua
vim.o.ruler = false
```
