### ISSUE TITLE
Trailing whitespace

### ISSUE THREAD

**Issue by Zane-** [glepnir/dashboard-nvim#135]
I have a plugin that highlights trailing whitespace as red, and dashboard-nvim has a lot of it. Can it please be removed?

**Comment by alphatroya** [comment]
Same problem, how did you solve it?

<img width="1322" alt="Screenshot 2023-02-06 at 09 41 17" src="https://user-images.githubusercontent.com/4927633/216924781-3e40d2f0-cce0-4304-9dd1-27b3e7e7e20e.png">

I use [Vim Better Whitespace Plugin](https://github.com/ntpeters/vim-better-whitespace) for whitespace highlighting.

**Comment by glepnir** [comment]
why you don't read this plugin. `g:better_whitespace_filetypes_blacklist`. i open it just now and find this in readme.

**Comment by alphatroya** [comment]
You are ahead of me) Thanks for help and great plugin. 

For future seachers, disable it by
```
vim.g.better_whitespace_filetypes_blacklist = { 'dashboard' }
```
