### ISSUE TITLE
BUG: Commit 801f50 breaks the session feature

### ISSUE THREAD

**Issue by LeonHeidelbach** [glepnir/dashboard-nvim#136]
@Neelfrost As the title says, your commit https://github.com/glepnir/dashboard-nvim/commit/801f50afe086906528d379c8d8d3a7a8d98775e7 breaks sessions for me. When opening a directory with nvim and loading the last session for this directory, only the last saved session is loaded regardless of the current working directory.

### Steps to reproduce:
* `cd ~/projects`
* `nvim .`
* `:SessionSave` -- We will call this "Session_1"
* `cd ~/.config/nvim`
* `nvim .`
* `:SessionSave` -- We will call this "Session_2"
* `cd ~/projects`
* `nvim .`
* `:SessionLoad` -- "Session_2" will be loaded even though we are not in the correct directory for "Session_2" and we expect "Session_1" to be loaded

### Expected behaviour:
After the above steps "Session_1" should be loaded for the `~/projects` directory, as it did before commit https://github.com/glepnir/dashboard-nvim/commit/801f50afe086906528d379c8d8d3a7a8d98775e7.

### System setup:
* OS: Arch Linux x86_64
* Kernel: 5.18.0-arch1-1
* NVIM v0.7.0:
  - Build type: Release
  - LuaJIT 2.1.0-beta3

**Comment by LeonHeidelbach** [comment]
@glepnir how long do you think this will take? If this will take a while, could you maybe just push a quick hotfix for this issue, since its a real pain to manually reset 3 commits each time I run `:PackerSync`.

**Comment by glepnir** [comment]
@LeonHeidelbach  you can use packer's keyword pin with  `commit` .

**Comment by LeonHeidelbach** [comment]
@glepnir after updating the commands `SessionSave` and `SessionLoad` are not even available anymore. Did you remove the session feature?

**Comment by glepnir** [comment]
https://github.com/Shatur/neovim-session-manager there has a instead plugin. yup I had remove session support

**Comment by LeonHeidelbach** [comment]
@glepnir I saw that you re-added session support in one of the last commits. This is really one of the key features of dashboard.nvim for me. I have tried to add the same session file directory as before the rewrite but this does not seem to work. When trying to read a session file for a directory, dashboard.nvim automatically creates a new session file inside the cwd regardless of the overridden session directory. When I try to save a session with my new session directory set like this (taken from your documentation):

```lua
local home = os.getenv('HOME')
local db = require('dashboard')
db.session_directory = home .. '/.cache/vim/session'
```

I get this error:

![Screenshot_20220616_215508](https://user-images.githubusercontent.com/55194243/174154212-af03cca4-3964-45b0-b8e7-2fbdadc8a124.png)

Apparently there is something wrong with setting the path and name for new session files as it trys to append the cwd to the session folder path which causes the above error.

**Comment by glepnir** [comment]
fixed

**Comment by LeonHeidelbach** [comment]
@glepnir the custom sessions directory override works now, thank you! However, it still creates a `Session.vim` file in the cwd every time I load a session.

![Screenshot_20220617_120403](https://user-images.githubusercontent.com/55194243/174276765-96e678cb-a1f6-40f2-9445-1c8a579a8590.png)

**Comment by glepnir** [comment]
fixed now

**Comment by LeonHeidelbach** [comment]
@glepnir works like a charm now. Thank you so much for the quick fixes, really enjoy the plugin :+1:.
