### ISSUE TITLE
Action missmatch

### ISSUE THREAD

**Issue by WalkerGloom** [glepnir/dashboard-nvim#141]
我用的是Windows上的neovim 0.7，
按照新的配置文件写好custom_center后，
在启动界面选择第1个action正确执行，选择第2个会执行第3个action，选择第3个会执行第5个action；
而且header会向右偏移，footer太靠上。希望可以修复，感谢作者大大的付出！！
<img width="960" alt="错误匹配" src="https://user-images.githubusercontent.com/50197664/173187108-072a038c-e4a8-4947-bbd4-0586cd6cac52.png">

**Comment by glepnir** [comment]
pos your min config here

**Comment by WalkerGloom** [comment]
local db = require('dashboard')
db.custom_header = {
  [[ ███╗   ██╗███████╗ ██████╗ ██╗   ██╗██╗███╗   ███╗]],
  [[ ████╗  ██║██╔════╝██╔═══██╗██║   ██║██║████╗ ████║]],
  [[ ██╔██╗ ██║█████╗  ██║   ██║██║   ██║██║██╔████╔██║]],
  [[ ██║╚██╗██║██╔══╝  ██║   ██║╚██╗ ██╔╝██║██║╚██╔╝██║]],
  [[ ██║ ╚████║███████╗╚██████╔╝ ╚████╔╝ ██║██║ ╚═╝ ██║]],
  [[ ╚═╝  ╚═══╝╚══════╝ ╚═════╝   ╚═══╝  ╚═╝╚═╝     ╚═╝]],
  [[                                                   ]],
  [[                [ version : 1.0.0 ]                ]],
}
db.custom_center = {
    -- 有bug，选择错位了
    -- 一行生效，二行跳三行，三行跳五行
    {icon = '    ',
    desc = 'Projects                                ',
    action = 'Telescope projects',
    shortcut = 'SPC s l'},
    {icon = '    ',
    desc = 'Recently opened files                   ',
    action =  'Telescope oldfiles',
    shortcut = 'SPC f h'},
    {icon = '    ',
    desc = 'Edit keybindings                        ',
    action = 'edit C:\\Users\\ggglo\\AppData\\Local\\nvim\\lua\\keybindings.lua',
    shortcut = 'SPC f f'},
    {icon = '    ',
    desc = 'Edit Projects                           ',
    action = 'edit C:\\Users\\ggglo\\AppData\\Local\\nvim-data\\project_nvim\\project_history',
    shortcut = 'SPC f b'},
    {icon = '    ',
    desc = 'Recently opened files                   ',
    action =  'Telescope oldfiles',
    shortcut = 'SPC f h'},
 }
 db.custom_footer = {"https://github.com/nshen/learn-neovim-lua"}

**Comment by WalkerGloom** [comment]
<img width="781" alt="miss3" src="https://user-images.githubusercontent.com/50197664/173187717-67d33d53-3f00-4354-9c89-802169457d66.png">
