### ISSUE TITLE
No status line when editing a new file

### ISSUE THREAD

**Issue by lukoshkin** [glepnir/dashboard-nvim#143]
I guess it is due to the latest update #139.

We have the following option
`db.hide_statusline      -- boolean default is true. it will hide statusline in dashboard buffer and auto open in other buffer`
-- which is good. It does show statusline for any other buffer except that of dashboard and (!) the one created with `:e newfile`. I think the latter was not intended.

**Comment by glepnir** [comment]
I add a patch,hope that can work for you

**Comment by lukoshkin** [comment]
I think the patch may have helped. At least, now nvim has the status line when you open a new file for editing. However, I am not sure I called `:e new`, likely it was `:enew` -- which is different. So, the problem is that you don't have the status line when creating an unnamed buffer.
![Screenshot from 2022-06-12 17-23-32](https://user-images.githubusercontent.com/44115822/173237846-81727d60-7c73-4ec3-929c-a116bc7e0dba.png)
