### ISSUE TITLE
Session commands were removed?

### ISSUE THREAD

**Issue by omarahm3** [glepnir/dashboard-nvim#149]
After upgrading the plugin i noticed that both `SessionLoad` and `SessionSave` no longer exists, and both will result in `Not an editor command`

So i was just curious what happened? were they removed and no longer supported? moved to separate plugin?

**Comment by glepnir** [comment]
@omarahm3  well i had a long time not in neovim .so i don't know there has any session plugin work with telescope? if not I will add session support later.

**Comment by glepnir** [comment]
https://github.com/Shatur/neovim-session-manager

https://github.com/natecraddock/sessions.nvim

so I think these plugin can do it better :)
