### ISSUE TITLE
call_line_action - Error on Keyboard Interrupt

### ISSUE THREAD

**Issue by alexeygumirov** [glepnir/dashboard-nvim#152]
When I try to open a file, which is already opened by another instance of NeoVIM, I am getting standard warning and selection between Open (Read-Only), Edit anyway, Recover, Quit, Abort.
As soon as I chose 'Abort`, I am getting following error:
```
E5108: Error executing lua ...share/nvim/plugged/dashboard-nvim/lua/dashboard/init.lua:208: Keyboard interrupt
stack traceback:
        [C]: in function 'cmd'
        ...share/nvim/plugged/dashboard-nvim/lua/dashboard/init.lua:208: in function 'call_line_action'
        [string ":lua"]:1: in main chunk
```

NeoVIM 0.7.0

**Comment by glepnir** [comment]
@alexeygumirov  need reproduce step
