### ISSUE TITLE
How to use LOLCAT in Dashboard Like the README.md

### ISSUE THREAD

**Issue by MRVAX** [glepnir/dashboard-nvim#153]
I LOOOOVE TO USE RAINBOW COLOR IN DASHBOARD LIKE IN README.md, and btw I want to know how to setting can manke the custom_footer have some empty line between custom_center ( except useing
```lua
db.custom_footer = {
    '',
    '',
    '',
    '',
    'xxxxxxxxxx'
}
```

**Comment by glepnir** [comment]
I had add an empty line before the footer .about rainbow in footer. it need create another terminal float window in footer . it's no necessary to do this.

**Comment by hexcowboy** [comment]
https://github.com/nvimdev/dashboard-nvim/issues/435#issuecomment-2041713835
