### ISSUE TITLE
When I opened the file via nvimTree, Dashboard was not closed

### ISSUE THREAD

**Issue by zlongCoding** [glepnir/dashboard-nvim#154]
When I opened the file via nvimTree, Dashboard was not closed
![7](https://user-images.githubusercontent.com/20821148/173498261-d21069ed-6ca5-4255-bdfd-d68816e96cc7.gif)

How should I solve this problem

**Comment by glepnir** [comment]
@zlongCoding  which keymap do you used to open file? check the nvim-tree mapping. I think you press a key that opne file in vsplit

**Comment by rafael-hs** [comment]
I have the same issue with nerdtree :/ @zlongCoding u got fix this?

**Comment by glepnir** [comment]
git init then open it will close ?

**Comment by glepnir** [comment]
should be works now.

**Comment by rafael-hs** [comment]
@glepnir I test your change, maybe the corret way is, delete buffer after select a file, the way it is now, it closes when the nerdtree opens

https://user-images.githubusercontent.com/26948732/189787125-643ac178-4f95-496c-a4d3-278d7a4bbdfc.mov

**Comment by rafael-hs** [comment]
@glepnir any update?

**Comment by glepnir** [comment]
already fixed？ not work for you？please update .

**Comment by rafael-hs** [comment]
same behavior, when I open the nerdtree, nerdtree takes up the entire screen, how I showed on the video above @glepnir
