### ISSUE TITLE
Commands are not available anymore?

### ISSUE THREAD

**Issue by leoluz** [glepnir/dashboard-nvim#158]
**Describe the bug**

It seems most of the commands were removed? 
Is there any guide users should follow to avoid breaking everything related to this plugin?

**To Reproduce**
```
:DashboardFindHistory
E492: Not an editor command: DashboardFindHistory
```
**Expected behavior**
previous command executed successfully

**Comment by leoluz** [comment]
Fixed my setup by specifying the commit before everything was broken.

If you are a packer user you can do this:
```
  use {
    "glepnir/dashboard-nvim",
    commit = "a36b3232c98616149784f2ca2654e77caea7a522",
}
```

**Comment by glepnir** [comment]
@leoluz  Sorry for break your config. in new lua version you can do it in action filed

**Comment by lamduong33** [comment]
I'm sorry, hate to bring back a dead thread, but what is "action filed"? I can't seem to get DashboardFindHistory to work. I'm pretty new to the lua config with neovim.

**Comment by glepnir** [comment]
you can pass `Telescope find_files` in `action` filed. like a button ? when you press enter it will trigger.

**Comment by lamduong33** [comment]
Telescope works just fine, but I wonder what happened to DashboardFindHistory with the new changes to dashboard?

**Comment by glepnir** [comment]
all command of dashboard just a function then call fuzzy finder command. so they are same.

`DashboardFindHistory` is `Telescope oldfiles`

**Comment by lamduong33** [comment]
Thanks! This should definitely be either in the wiki or the README.md
