### ISSUE TITLE
Error Detected while processing 'BufWinEnter' Autocommands for '*'

### ISSUE THREAD

**Issue by Im-Kal** [glepnir/dashboard-nvim#159]
**Describe the bug**
The below image always show when I open up Neovim, did TSUpdate and PackerSync yet it persists

**Screenshots**
![image](https://user-images.githubusercontent.com/69103102/174848894-e77fd9c5-6b08-48f3-934b-194925134b44.png)

**Comment by Im-Kal** [comment]
Windows 11 btw

**Comment by Erven2016** [comment]
Hello, this code of line 29 in session.lua was commited by me, and I am also using neovim on Windows 11, but I have not see the error likes yours.

![image](https://user-images.githubusercontent.com/18652605/174932909-54fa9fe3-b71a-420c-a514-ce2d2a738bf8.png)

I have checked the type of db variable, it looks like a `table` instead of `boolean`.

Can you show me what version of neovim and packer that you are using?

**Comment by glepnir** [comment]
@Im-Kal  your pic looks wired. I think you should use a min config to check does this error come from dashboard or your neovim config

**Comment by Im-Kal** [comment]
![image](https://user-images.githubusercontent.com/69103102/175074534-91f7c88b-e326-4fb7-8897-e509f66d9915.png)
`vim.g.dashboard_custom_header = {
 [[                           ▓▓▓▓▓▓▓     ]],
 [[                       ▓▓▓▓▓▓▓▓▓▓▓▓▓▓  ]],
 [[                     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]],
 [[                   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]],
 [[  ▓▓             ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]],
 [[▓▓▓▓▓▓▓        ▓▓▓▓▓▓▓▓▓▓▓▓▓ ▒▓▓▓▓▓▓▓▓▓]],
 [[▓▓▓▓▓▓▓▓▓▓   ▓▓▓▓▓▓▓▓▓▓▓▓    ░▓▓▓▓▓▓▓▓▓]],
 [[  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓      ░▓▓▓▓▓▓▓▓▓]],
 [[    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓         ▓▓▓▓▓▓▓▓▓▓]],
 [[      ▓▓▓▓▓▓▓▓▓▓▓▓           ▓▓▓▓▓▓▓▓▓▓]],
 [[    ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓         ▓▓▓▓▓▓▓▓▓▓]],
 [[  ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓      ▒▓▓▓▓▓▓▓▓▓]],
 [[▓▓▓▓▓▓▓▓▓▓   ▓▓▓▓▓▓▓▓▓▓▓▓    ▒▓▓▓▓▓▓▓▓▓]],
 [[▓▓▓▓▓▓▓        ▓▓▓▓▓▓▓▓▓▓▓▓▓ ▒▓▓▓▓▓▓▓▓▓]],
 [[  ▓▓             ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]],
 [[                   ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]],
 [[                     ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓]],
 [[                        ▓▓▓▓▓▓▓▓▓▓▓▓▓  ]],
 [[                          ▓▓▓▓▓▓▓      ]],
 [[                                       ]],
 [[             Start Editing             ]]
}

vim.g.dashboard_default_executive = 'telescope'

vim.g.dashboard_custom_section = {
    a = {description = {'  File Browser       '}, command = 'Telescope file_browser'},
    d = {description = {'  Search Text        '}, command = 'Telescope live_grep'},
    b = {description = {'  Recent             '}, command = 'Telescope oldfiles'},
    f = {description = {'  Git Status         '}, command = 'Telescope git_status'}
}

vim.g.dashboard_custom_footer = {
  [[            Visual Studio Code               ]],
  [[             Editing evolved                 ]]
}

`

My config ^^^

**Comment by glepnir** [comment]
@Im-Kal  you used old options that had removed. please check readme for new options
