### ISSUE TITLE
calculate preview dimensions automatically

### ISSUE THREAD

**Issue by bennypowers** [glepnir/dashboard-nvim#162]
**Is your feature request related to a problem? Please describe.**
Follow-up to #161. When preview_file_path is dynamic, `preview_file_width` and `preview_file_height` may not be known in advance. 

**Describe the solution you'd like**
In those cases, let the dimensions be calculated automatically from the file contents (or, from the output of the command)

**Describe alternatives you've considered**
make those functions also dynamic, such that it becomes the user's problem

**Comment by glepnir** [comment]
in `preview_file_width` you get get the content width also you can get height? then set `preview_file_height` in width function. what do you think?

**Comment by bennypowers** [comment]
This _kind of_ works:

```lua
db.preview_command = "cat | sed '$d'"
db.preview_file_height = 40
db.preview_file_width = 80
db.preview_file_path = function()
  local headers_dirnames = { headers_basedir .. 'small' }

  if vim.fn.winwidth('%') >= 100 then
    table.insert(headers_dirnames, headers_basedir .. 'wide')
  end

  if vim.fn.winheight('%') >= 60 then
    table.insert(headers_dirnames, headers_basedir .. 'large')
  end

  local headers = {}

  for _, dirname in ipairs(headers_dirnames) do
    for _, filename in ipairs(vim.fn.readdir(dirname)) do
      table.insert(headers, dirname .. '/' .. filename)
    end
  end

  local path = headers[math.random(1, #headers)]

  local lines = vim.fn.readfile(path)
  db.preview_file_height = #lines
  local max = 0
  for _, line in ipairs(lines) do
    if string.len(line) > max then
      max = #line
    end
  end
  db.preview_file_width = max

  vim.notify(vim.inspect { db.preview_file_width, db.preview_file_height })
  return path
end
```

But there are a few issues:
1. there has to be a numerical value initially set, otherwise
    ```
    Error detected while processing CursorMoved Autocommands for "<buffer=7>":
    Error executing lua callback: .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:262: attempt to perform arithmetic on a nil value
    stack traceback:
            .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:262: in function 'set_cursor'
            .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:402: in function <.../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:399>
    ```
2. Those initial values are what are actually applied, not the dynamically-set ones from the `preview_file_path` call
2. I'm duplicating work, since the file will be read by `cat`
3. see that `string.len` call? it doesn't strip ansi escapes. Yes, PEBCAK, but an internal impl could save the user the headache

**Comment by glepnir** [comment]
I guess now should work.
