### ISSUE TITLE
Is it possible to have a empty custom center section?

### ISSUE THREAD

**Issue by suessflorian** [glepnir/dashboard-nvim#164]
A non-specified configuration yields a `Please Config your own center section`. Can we remove it entirely? Keen to have a nice splash screen without anything else.

**Comment by suessflorian** [comment]
What a fun plugin btw, thanks 🙏

**Comment by glepnir** [comment]
you can config like this

db.custom_center ={ { desc =" "}}
db.custom_footer ={" "}
