### ISSUE TITLE
Override the default theme for dashboard

### ISSUE THREAD

**Issue by stevie-b-g** [glepnir/dashboard-nvim#165]
I'm currently using gruvbox theme and the dashboard does not look that pretty.

It would be great if there was a config to override the default theme for the dashboard so I can see it to something prettier like the screenshots.

**Comment by glepnir** [comment]
check your colorscheme has the dashboard highlight group ，if not you need config them in your neovim configs all of dashboard highlight group you can found in readme .usage like
 hi DashboardHeader guifg=your color code
