### ISSUE TITLE
Grey Block on Dashboard

### ISSUE THREAD

**Issue by charliesabino** [glepnir/dashboard-nvim#166]
**Describe the bug**
Weird grey character appearing on my dashboard

**To Reproduce**
when applying my custom logo in my .config/neovim/static/neovim.cat file

**Expected behavior**
For no grey block to ruin the aesthetic

**Screenshots**

<img width="708" alt="CleanShot 2022-06-29 at 22 14 55@2x" src="https://user-images.githubusercontent.com/94320712/176597980-09c25b9d-736a-4711-808f-e95b6b8c73b5.png">
<img width="749" alt="CleanShot 2022-06-29 at 22 15 18@2x" src="https://user-images.githubusercontent.com/94320712/176598013-9b7d7013-8984-4697-b1e1-77ac5e8d524d.png">
<img width="744" alt="CleanShot 2022-06-29 at 22 16 03@2x" src="https://user-images.githubusercontent.com/94320712/176598078-eadc2a11-fad5-462b-9b79-6d0d784064cd.png">

**Comment by glepnir** [comment]
reduce width value

**Comment by glepnir** [comment]
post your cat file here i will test later

**Comment by charliesabino** [comment]
It was the height
