### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by spelb** [glepnir/dashboard-nvim#167]
Hi, sorry to bother you but need a little help.  I want a simple dashboard setup like
when neovim opens it displays Neovim at the top instead of Dashboard and below it should display the neovim version instead of plugin version.
and i want to add 3 option at center.
1. Last opened file
2. New file
4.  Settings ( which will open the main init.lua file)
Please guide me  as I have no knowledge about lua. Thanks
I kept all my config in 1 file (init.lua) which is my custom setup and I can show it to youl
My Neovim config is very simple and clean.
you can see my simple config at : https://github.com/spelb/nvim-config

**Comment by glepnir** [comment]
```lua
local dashboard = require('dashboard')
dashboard.custom_center = {
      {icon = '  ',
      desc = 'Recently opened files                   ',
      action =  'Telescope oldfiles',
      shortcut = 'SPC f h'},
      {icon = '  ',
      desc ='New File                            ',
      action =  'DashboardNewFile',
      shortcut = 'SPC f b'},
      {icon = '  ',
      desc = 'Settings                            ',
      action = ':edit ~/.config.nvim/init.lua',
      shortcut = 'SPC f b'},
}

dashboard.custom_footer = {  {vim.v.version} }
```
