### ISSUE TITLE
更新后设置的g:dashboard_custom_header没有生效。

### ISSUE THREAD

**Issue by yuzhen1024** [glepnir/dashboard-nvim#169]
目前的启动界面
![Screenshot_20220711_153013](https://user-images.githubusercontent.com/47154428/178212244-faed5c43-a0a7-4ab8-8d6a-eef87c5f7903.png)

`:echo dashboard_custom_header`
![Screenshot_20220711_153354](https://user-images.githubusercontent.com/47154428/178212184-f5ee6486-ae5e-4f50-83d2-813d12ae01b1.png)

常年使用没有出现该状况，问题出现在近期，今天被发现。

**Comment by glepnir** [comment]
看文档 。重写了 。
