### ISSUE TITLE
Padding between `custom_center` components

### ISSUE THREAD

**Issue by olimorris** [glepnir/dashboard-nvim#172]
**Is your feature request related to a problem? Please describe.**
Firstly, thank you for the unbelievably swift work with #171. I think it's a great addition to the plugin. This request follows on from that and is concerned with padding between items in the `custom_center` table.

**Describe the solution you'd like**
On my laptop, the spacing between items in the `custom_center` table is large:

![Screen Shot 2022-07-11 at 16 55 14@2x](https://user-images.githubusercontent.com/9512444/178306057-921cfd12-9015-4f8b-9c67-31472d32da74.png)

I would love to be able to specify the padding between items such as:

```lua
  db.custom_center = {
    {
      icon = "  ",
      desc = "Recently latest session                 ",
      shortcut = "SPC s l",
      padding = 2,
      action = "SessionLoad",
    },
    {
      icon = "  ",
      desc = "Recently opened files                   ",
      action = "DashboardFindHistory",
      padding = 0,
      shortcut = "SPC f h",
    },
    {
      icon = "  ",
      desc = "Find  File                              ",
      action = "Telescope find_files find_command=rg,--hidden,--files",
      padding = 1,
      shortcut = "SPC f f",
    },
}
```

**Additional context**
It would be nice to group some items (e.g. telescope extensions) together via padding or keep them tightly bunched when `winheight` is a small number.

**Comment by glepnir** [comment]
It' only one space between the items in center. I don't like to config pad for every item. it looks like wired
```
|test item   |
|
| test items1|
| test items2|
```
