### ISSUE TITLE
Same unicode icon rendered differently at center and footer

### ISSUE THREAD

**Issue by gustavomtborges** [glepnir/dashboard-nvim#173]
I set the same unicode icon U+e30c at custom_center and custom_footer, but they rendered differently on dashboard. I'm using kitty terminal.

Screenshots:
![Screen Shot 2022-07-15 at 13 34 59](https://user-images.githubusercontent.com/4812010/179269280-fe23405d-bd90-43de-8e5e-0f7e6a51232b.png)
![Screen Shot 2022-07-15 at 13 34 42](https://user-images.githubusercontent.com/4812010/179269299-f6bd0fac-d111-4370-b8b1-e5a44e4285d2.png)

**Comment by glepnir** [comment]
remove desc= in footer

**Comment by gustavomtborges** [comment]
> 

Same result

**Comment by glepnir** [comment]
I test it works fine . 

![image](https://user-images.githubusercontent.com/41671631/179379256-6e0c53dc-142a-403f-87f2-d61d126a65e7.png)
