### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by spelb** [glepnir/dashboard-nvim#177]
Hi, Sorry to bother you once again but I have 2 issues for which I wanted your help.
1. when I open neovim the dashboard appears as the center but upon resizing the terminal  while keeping neovim open the dashboard does not adjust itself at the center.
2. you can see in the screenshots below the column numbers and all written. I want that to be removed . Thanks
![s0](https://user-images.githubusercontent.com/108426549/181363920-9b932495-8229-4c57-a5d6-b7bcbcc1c4de.png)
![s1](https://user-images.githubusercontent.com/108426549/181363946-692ef21a-3ec5-45d9-9301-d7931a8f9198.png)

**Comment by glepnir** [comment]
fix it later
