### ISSUE TITLE
custom_header text with newline doesn't display 

### ISSUE THREAD

**Issue by ashleyx** [glepnir/dashboard-nvim#179]
**Describe the bug**

With one of the recent updates custom headers  that were previously working no longer works. I think the issue is when there is a new line character in the text.

**To Reproduce**
minimal config used to run nvim -u config
```
return require('packer').startup(function(use)
	use {'glepnir/dashboard-nvim', -- dashboard on vim startup 
		config = function()
			local home = os.getenv('HOME')
			local db = require('dashboard')
			db.custom_header = 	{[[
			TEST
			]]}
		end
	}
	
  if packer_bootstrap then
    require('packer').sync()
  end
end)

```

**Expected behavior**

Previously it would display TEST in header.
`db.custom_header = 	{[[TEST]]}` still works

**Screenshots**
No Header being displayed
![image](https://user-images.githubusercontent.com/26083457/181431955-aa0cf2e8-8fb1-4e00-97a5-ff77b5950e81.png)

Another weird behavior i noticed was setting `db.custom_header =  {'TEST','TEST','TEST','TEST'}` causes an extra newline before the last element 
![image](https://user-images.githubusercontent.com/26083457/181432298-4280e973-df30-494b-8a42-0929e8feed06.png)

**Comment by Erven2016** [comment]
you can try that adding a blank line to last line like:

```lua
db.custom_header = {
'test',
'test',
'test',
'test',
'',
}
```

**Comment by glepnir** [comment]
you should check the `[[ ]]` usage in lua . if you want add some pad . check the doc for pad option

```lua
db.custom = { 'test' }
``

**Comment by ashleyx** [comment]
This no longer works 
```
local home = os.getenv('HOME')
return require('packer').startup(function(use)
	use {'glepnir/dashboard-nvim', -- dashboard on vim startup 
		config = function()
			local home = os.getenv('HOME')
			local db = require('dashboard')
			db.preview_command = 'cat '
			db.preview_file_path = home .. '/temp/test.txt'
			db.preview_file_height = 50
			db.preview_file_width = 50
		end
	}
	
  if packer_bootstrap then
    require('packer').sync()
  end
end)
```

with test.txt as
```
test
test
```
does not work while it used to work previously. 
`db.preview_command = 'cat | lolcat'` works. 

I was previously using a binary file that already had color in it and printing it with just cat.That is now broken.  I cant figure out what i need to change to get it to work again. i thought it was the newline that was causing the issue, looks like i was mistaken.

**Comment by ashleyx** [comment]
`cat | cat` worked lol.

**Comment by glepnir** [comment]
so it works now?

**Comment by ashleyx** [comment]
yes. changing the preview_command from `cat ` to `cat | cat` fixed it.

**Comment by glepnir** [comment]
Okay but I think `cat` also should work. I will check it when i have time :)
