### ISSUE TITLE
dashboard issue

### ISSUE THREAD

**Issue by spelb** [glepnir/dashboard-nvim#182]
Hi, Thanks alot for solving the issue. Now there are only 2 small issues left.
1. The dashboard adjsult itself at the center from left to right upon resizing but does not adjust to center from top to bottom.
2. custom_footer section sometimes gets close to the custom_center section when opening neovim and sometimes it is at its place.
3. The footer section on the 2nd image is at the correct place while in the 1st its too close to center section.
4. Please fix 2 issues. Thanks
![s1](https://user-images.githubusercontent.com/108426549/181478997-8205ffea-733f-49fe-b141-9143b7c5a792.png)
![s2](https://user-images.githubusercontent.com/108426549/181479152-507b1a62-4bf8-47bd-9e94-a1bb2f95b0a5.png)

**Comment by glepnir** [comment]
Please read doc there has pad option

**Comment by spelb** [comment]
@glepnir where is the doc? and the custom_footer sometimes is too close to center section and sometimes at its correct place

**Comment by glepnir** [comment]
The window change from top to bottom doesn't make any sense to me. dashboard resize doesn't work for this case. if you want do this PR welcome.

**Comment by spelb** [comment]
@glepnir yes i saw the doc thanks. and what about the footer section changing its place in different nvim opening sections?
