### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by spelb** [glepnir/dashboard-nvim#184]
Hi, there is another bug in the code.
I added Update Plugins option to the dashboard custom center and it works fine but when I update plugins using the option then the cursor changes its position when I close the Packer window and the cursor then starts moving in the empty lines. Please fix
![s2](https://user-images.githubusercontent.com/108426549/181615878-c77b6ebd-2927-430b-8fe2-905439786344.png)
this is my config
![s3](https://user-images.githubusercontent.com/108426549/181615943-970696f2-68ca-4abb-84ad-365b2efcb99f.png)
this pic is of before updating plugins.
![s4](https://user-images.githubusercontent.com/108426549/181616032-54a97187-2f27-4b88-b429-7327a20ebf4c.png)
![s5](https://user-images.githubusercontent.com/108426549/181616053-c6f64584-ebc2-4c7b-ba32-e76033a23173.png)
and after updating plugins when I close packer by 'q' then the cursor is on empty lines.

**Comment by glepnir** [comment]
I can't reproduce your problem. then there has issue template you must fill issue template not post lots of image ? please learn how to use github
