### ISSUE TITLE
db issue

### ISSUE THREAD

**Issue by spelb** [glepnir/dashboard-nvim#185]
Hi, The header text in dashboard is not showing well. Most likely this is a bug. And when I Update Plugins then the cursor is placed on the empty lines in the dashboard instead of options. My lua config for dashboard is correct. Please fix the header text bug and the cursor position. 
1.Look The header text has 1 line space and the last line of  header text is separated as you can see. 
2.I use packer's floating window for packer's operation. When use the Update Plugins option then packer opens up its float window for updating plugins. When I close the packer's float window using q then the cursor is on the empty lines as you can see below.Thanks
![s0](https://user-images.githubusercontent.com/108426549/181687228-a9ecfec5-2264-4441-b8fd-400792fd4f6b.png)

**Comment by glepnir** [comment]
issue template Please !!

**Comment by spelb** [comment]
> issue template Please !!

what you mean by template?
