### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by spelb** [glepnir/dashboard-nvim#187]
HI, since you did not understand about the issue i'm having , I decided to create a video about it so you will see them clearly .
You can see in the video that after using the Update Plugin option , the cursor is not at options but instead at the empty spaces. and the NEOVIM text header issue.

https://user-images.githubusercontent.com/108426549/181743226-bfdbbfcc-acf7-441f-8008-876e40548485.mp4

Also have a look at my complete dashboard-config .
![s1](https://user-images.githubusercontent.com/108426549/181743363-527891da-27d8-40b2-9884-241bb0a886f7.png)

Note: You can see in the video at header text in neovim and my dashboard-config so it is to be fixed.
here is my complete neovim setup at Gitlab.
https://gitlab.com/neovim1/nvim-config

**Comment by glepnir** [comment]
please fill issue template .

![image](https://user-images.githubusercontent.com/41671631/181745603-edd8bd48-e75b-4fa0-b716-9d23c73b5c42.png)

**Comment by glepnir** [comment]
issue template had what i need and with a min config. Please learn how to use github and how to ask a question.

**Comment by glepnir** [comment]
https://github.com/glepnir/dashboard-nvim/issues/179 do like this

**Comment by spelb** [comment]
Bug Description:
1.The bugs are that when I open neovim my header text is  separated in 2 parts. The last line of my header text is shown below from the other lines of the header text.
2. When I run Update Plugins option from dashboard it performs action = ':PackerSync' and a floating window of packer is displayed for updating plugins. But when I close the packer's floating window by pressing 'q' after updating plugins.
The cursor position is moved to the empty space above Update Plugins option in dashboard.

Expected behaviour:
1. The header text should display correctly without the last line being separated to the center section.
2. After updating plugins the cursor position should be placed on the Update Plugins option where it was before updating plugins when I close the packer's floating window.

Screenshots of the bugs:

![s3](https://user-images.githubusercontent.com/108426549/181748219-b529ca2e-6ea3-4bca-9f9c-691b8812f70d.png)

Now this is the github template and described everything in details.
Note: Look at the cursor position in the screenshot and the last line of header text being separated. (This screenshot is taken after using Update Plugins option.)

**Comment by glepnir** [comment]
hmmm did you read the issue template and google it how to fill it? i had give you an example. you need provide a min config that can reproduce your problem.  You need to understand the flow of open source work.

![image](https://user-images.githubusercontent.com/41671631/181749829-798f61ba-0a72-4304-aebe-91052557b17f.png)

**Comment by spelb** [comment]
@glepnir I only know the very basics of lua which I learned for neovim. and I already provided Bugs' description. My config and even video which describes the bug clearly.

**Comment by glepnir** [comment]
you need provide a min config that can reproduce . then author can use it reproduce it and fix. we don't spend any time to check your config . there are many plugins in everyone's configuration. We can't spend time to check what happen in their config, so min config is necessary.  I hope you understand. No plugin author will like your way of submitting issues.

**Comment by spelb** [comment]
okay here is my min config. its the dashboard config. 
[p.txt](https://github.com/glepnir/dashboard-nvim/files/9219715/p.txt)

Note: There are two issues. 
1. The header text is separated in 2 parts.
2. When you use the update plugins option and then the cursor auto changes its position to the empty space above Update Plugins option.( I configured packer to use floating window for its operations )
![s3](https://user-images.githubusercontent.com/108426549/181755021-2b970a20-1e25-4067-88d6-d8edd783f693.png)

**Comment by glepnir** [comment]
not image !!!!!please check the example and learn how to use markdown to insert code.

**Comment by spelb** [comment]
`local db = require('dashboard')

db.custom_header = {
[[♥♥♥    ♥♥ ♥♥♥♥♥♥♥  ♥♥♥♥♥♥  ♥♥    ♥♥ ♥♥ ♥♥♥    ♥♥♥]],
[[♥♥♥♥   ♥♥ ♥♥      ♥♥    ♥♥ ♥♥    ♥♥ ♥♥ ♥♥♥♥  ♥♥♥♥]],
[[♥♥ ♥♥  ♥♥ ♥♥♥♥♥   ♥♥    ♥♥ ♥♥    ♥♥ ♥♥ ♥♥ ♥♥♥♥ ♥♥]],
[[♥♥  ♥♥ ♥♥ ♥♥      ♥♥    ♥♥  ♥♥  ♥♥  ♥♥ ♥♥  ♥♥  ♥♥]],
[[♥♥   ♥♥♥♥ ♥♥♥♥♥♥♥  ♥♥♥♥♥♥    ♥♥♥♥   ♥♥ ♥♥      ♥♥]],
}
db.header_pad = 2

db.custom_center = {
      {
          desc = 'Recent Files                   ',
          action =  ':browse oldfiles',
          shortcut = '...'
      },
      {
          desc ='New File                       ',
          action =  'DashboardNewFile',
          shortcut = '...'
      },
      {
          desc = 'Settings                       ',
          action = ':e ~/.config/nvim/lua/settings/init.lua',
          shortcut = '...'
      },
      {
          desc = 'Update Plugins                 ',
          action = ':PackerSync',
          shortcut = '...'
      },
      {
           desc = 'Quit                           ',
           action = ':q',
           shortcut = '...'
       }
}
db.center_pad = 1

db.custom_footer = { desc = 'It is never too late to become what you never were.' }
db.footer_pad = 2
`

**Comment by glepnir** [comment]
you need learn how to use markdown i think
1. fixed. 2. i don't use a float packer. and works fine with telescope floatwindow.

**Comment by spelb** [comment]
> you need learn how to use markdown i think
> 
>     1. fixed. 2. i don't use a float packer. and works fine with telescope floatwindow.

@glepnir okay Thank You so much. and I'm extremely sorry for all this. I really don't know about github much and yes I will learn markdown. thanks but the 2nd issue with packer float window is really annoying . Can you please look at the video above I posted to see the bug with packer's floating window? OR 
add this at the end of the packer-config you are using. 
`config = {
  display = {
    open_fn = function()
      return require('packer.util').float({ border = 'single' })
    end
  }}`

**Comment by spelb** [comment]
@glepnir add the above code at the very end of the packer-config to use. `packer.startup({function()
  -- Your plugins here
end,
config = {
  display = {
    open_fn = function()
      return require('packer.util').float({ border = 'single' })
    end
  }
}})`
