### ISSUE TITLE
statusline and tabline show up in dashboard

### ISSUE THREAD

**Issue by spelb** [glepnir/dashboard-nvim#189]
**Describe the bug**
When I open neovim and the  dashboard appears. I ran the command `:h browse` to see the doc of vim. But when I closed the doc page by `:q` then the tabline and statusline appeared in the dashboard as well.

**To Reproduce**
1. Open neovim and run the command   `:h browse` (or any other command like `:h omnicfunc` ).
2. Close the doc  by command `:q` and you will see both statusline and tabline in dashboard.

**Expected behavior**
When I close the doc by command `:q` the tabline and statusline should also be gone instead of appearing up in the dashboard.

**Screenshots**

![s7](https://user-images.githubusercontent.com/108426549/181824509-3190e1e3-5e19-4d97-9a93-865d00c227fb.png)

**Comment by glepnir** [comment]
expect behavior
