### ISSUE TITLE
Resize issues

### ISSUE THREAD

**Issue by spelb** [glepnir/dashboard-nvim#190]
**Describe the bug**
HI again, There are  2 more issues with the dashboard.
1. When I open neovim and the dashboard appears, I pressed F11 key to maximize the screen. But then the Quit option in my dashboard doesn't work. I then opened opened neovim in full screen and pressed F11 to disable the full screen and then Quit option was not working while others were. When I don't use F11 to max or min the terminal screen then the Quit option works but after pressing F11 it does not.(my Quit option performs the `action = :q` )
2. After the pressing F11 to max or min the terminal screen , and then open a file from the dashboard( whether its Newfile or the Settings) then statusline and tabline are not shown. But when not pressed F11 to max or min then everything works fine.

**To Reproduce**
**Min config for quit option**
```ruby
{ desc = 'Quit',
  action = ':q' },
{ desc = 'New File',
  action = 'DashboardNewFile' }
```

1. Open neovim in terminal and press F11, you will then see that the Quit option will not work.
2. Open neovim is opened and you pressed F11 then click on the New File option or the Settings option in your dashboard and you will see statusline and tabline will not show up.

The dashboard is affected by  F11 key and the options of dashboard doesn't work well.

**Expected behavior**
When I press F11 to max out or min the terminal screen then the Quit option needs to work and when I open files by the dashboard newfile option ( or settings option) then the statusline and tabline should also show up.

**Screenshots**
Quit option doesn't work and opening files from dashboard option dosen't show up tabline and statusline.

![s8](https://user-images.githubusercontent.com/108426549/181828314-8290fc91-7b9f-4701-bdee-63ab2d36e78b.png)

**Comment by spelb** [comment]
Important Update: the above issues are not just by pressing F11 but occurs after resizing. I opened up my terminal and ran neovim. then resized the terminal and the above issues occured. So its by resizing

**Comment by glepnir** [comment]
I can't reproduce it. resize neovim and do quit action .works fine  `F11` this is your terminal and your env.I am not work for this.
