### ISSUE TITLE
Resizing & statuslines

### ISSUE THREAD

**Issue by spelb** [glepnir/dashboard-nvim#191]
**Describe the bug**
HI, There are still 2 bugs in dashboard. 
1. When I open neovim and dashboard appears then I ran the command `:h browse` (or any other command like `:h showmode` )
then the doc appears for that particular command but when I close the doc by `:q` then the doc disappears but the statusline and tabline still show up in dashboard also.
2. When I open up neovim in terminal and dashboard appears then I resized the terminal but that resized have 2 problems.

- The Quit option which actions = `:q` stops working after resizing.
- Other options in dashboard for files doesn't work well. After resizing the terminal while keeping neovim open the New File and settings option of dashboard works but they don't dispaly the statusline and tabline in new file opened from dashboard option after resize. ( new file in dashboard actions = `DashboardNewFile` and settings in dashboard actions = `:e ~/.config/nvim/lua/setttings/init.lua` ) 

**To Reproduce**
1. Open up neovim in terminal and run `:h browse` or any other help command. Then close the doc by `:q` and you will see the statusline and tabline in dashboard appeared.
2. Open up neovim in terminal and the resize the terminal by increasing size of terminal. then you will see the Quit option stops working and New File option to not display statusline and tabline in new file.

**Min config**

```ruby
{ desc = 'Quit',
  action = ':q' },
{ desc = 'New File',
  action = 'DashboardNewFile' }
```

**Expected behavior**
Dashboard should not be affected by resizing the terminal and statusline and tabline should not be appeared in dashboard after closing the doc for an option in dashboard.

**Screenshots**
This is a screenshot when I resized the terminal, Quit option stoped working and settings option and New file option opened without displaying statusline and tabline.
Note: I can quit the dashboard even after resizing the terminal by typing `:q` command but the Quit option which do the same `:q` stops working and other files option gets affected too)
 
![s8](https://user-images.githubusercontent.com/108426549/181877591-40f5904a-a758-4793-9605-505c9eb81b00.png)

This is a screenshot of statusline and tabline appeared in dsahboard after closing doc for a vim/neovim command.

![s7](https://user-images.githubusercontent.com/108426549/181877997-142586e2-38bc-445f-a70d-14b630532049.png)

**Comment by glepnir** [comment]
like i said this is expect behavior . if you don't like this PR welcome.

**Comment by spelb** [comment]
@glepnir and what about the resize issues? Can you please fix those. Just open neovim in terminal and then inrease the size of your terminal and you will see.

**Comment by glepnir** [comment]
I use window tiling program. Unable to test your window behavior. Resize neovim via tmux works fine. So I can't work for your environment

**Comment by spelb** [comment]
@glepnir  the isssue is in tmux also. I just used to tmux to test the resize issue and the issue is there. 
Which OS are you using? I'm user of Artix Linux with mate-terminal and desktop. 

![s00](https://user-images.githubusercontent.com/108426549/181879377-972d783e-a916-474c-a459-6f9493611745.png)

Dunno whats the problem, maybe my terminal problem.

**Comment by glepnir** [comment]
can't reproduce.
![issue](https://user-images.githubusercontent.com/41671631/181879494-d317e2af-1d5f-43b9-b6d3-85c52aae9600.gif)

**Comment by spelb** [comment]
@glepnir  I will try another desktop environment in the new Artix realese when it comes out. I think the problem is in my mate terminal.

**Comment by spelb** [comment]
@glepnir sorry to bother you once again but the issue is not in terminal as I checked it on another laptop with lxde desktop having lxde terminal. Please try this resize error without tmux in the os default terminal. I need to close neovim whenver resized.

**Comment by glepnir** [comment]
why lots of people not these question ? I think you should check the usage. some times not make sense I think. it just a simple start screen plugin. just use once on neovim start. Don't make it complex.
