### ISSUE TITLE
custom_header centering issues

### ISSUE THREAD

**Issue by lorecast162** [glepnir/dashboard-nvim#192]
**Describe the bug**
Header is centered when using `db.preview_file` but is not when using `db.custom_header`.
In my config (which is at https://github.com/lorecast162/dotfilesVIM) I have a file called logo ( [here](https://github.com/lorecast162/dotfilesVIM/blob/2ec4827fe12d852a0e24427678b18fffc16f8df0/logo) ) which is what `db.preview_file` would be set to.
I pasted its contents in my config adding `'`s where needed to make sure nvim picked it up as a multiline string (and manually adding some spaces at the start of lines as otherwise they'd all be wonky and misaligned, had to go through trial and error, but it seems I needed to add double the spaces every line... not sure tho)

N.B.: in the screenshot there is color highlighting various sections which I still have not pushed to my repo but that's the only difference (this bug also presented itself before adding the Highlight commands)

**To Reproduce**
Based on what I would do with my config:
1. Uncomment block starting at https://github.com/lorecast162/dotfilesVIM/blob/f0dfdf5b67c2dee62c746ecf178c1fb58f040a6f/init.vim#L241
2. Comment lines referring to `db.preview_*` (in this case I commented from line 232 to line 238 and then 261 and 262)
3. Run neovim
4. See that header is misaligned and not centered

**Expected behavior**
The text should be centered.

**Screenshots**
Using `db.preview_file`:
![Screenshot from 2022-07-30 12-35-30](https://user-images.githubusercontent.com/17319563/181906790-ba266f87-9018-4248-bf34-66221f9dd255.png)

Using `db.custom_header`:
![image](https://user-images.githubusercontent.com/17319563/181907684-92971732-ee42-41cd-b497-0aac2b65e0f7.png)

**Comment by lorecast162** [comment]
I have created a separate branch available at https://github.com/lorecast162/dotfilesVIM/blob/db-%3Efile-to-custom_header/init.vim where I do these edits.

**Comment by glepnir** [comment]
because your ascii text has lots of spaces at the line head

**Comment by lorecast162** [comment]
What should I do then, put some pipe characters around so it doesn't start with spaces?

**Comment by glepnir** [comment]
oh wait. the second is correct. use preview file it use a floatwindow to show. all texts just set into it. use ascii text dashboard will fill spaces .

**Comment by glepnir** [comment]
if you don't like the second . you can use preview file with lolcat cli tool make it rainbow or reduce the length of your ascii text. or use image if you are use linux.

**Comment by lorecast162** [comment]
Actually in the meantime I did what I said in my previous message and I say it looks quite nice (I'll replace the pipes and dashes with proper angled pipes to make it look better)
![image](https://user-images.githubusercontent.com/17319563/181908456-dde85427-ab7e-4114-bb44-e2938292b78f.png)

**Comment by lorecast162** [comment]
Thanks for your advices tho ^^
I'll close this.

**Comment by glepnir** [comment]
most welcome
