### ISSUE TITLE
how to remove neovim loaded plugin or how to add the party icon in arch

### ISSUE THREAD

**Issue by sbd26** [glepnir/dashboard-nvim#196]
party icon is not showing 
currently i am using axyl os 
how to fix this
or how to remove party icon or remove the loaded line :3 from the dashboard

![Screenshot_2022-08-05-11-02-55_1366x768](https://user-images.githubusercontent.com/93975218/183127189-c13b32c7-c751-47aa-8b23-229c8188acb3.png)

**Comment by glepnir** [comment]
db.custom_footer
