### ISSUE TITLE
How to hide cursor on dashboard?

### ISSUE THREAD

**Issue by Matelasse** [glepnir/dashboard-nvim#200]
Hi. I'm using my dashboard without any entries and navigation, I just map my keys to actions and use those keys. On dashboard I only have art displaying. So I want to hide the cursor completely. Is this possible?

**Comment by glepnir** [comment]
I think it's impossible in tui but can change it in gui? just found some articles for you 
https://superuser.com/questions/712098/customize-vim-cursor-style-under-mac-os-x-terminal
https://vim.fandom.com/wiki/Configuring_the_cursor
