### ISSUE TITLE
Ueberzug conflict with mksession

### ISSUE THREAD

**Issue by EpsilonKu** [glepnir/dashboard-nvim#203]
**Describe the bug**
Ueberzug image stay on other buffer when I autoload with mksession. I use https://github.com/olimorris/persisted.nvim . Maybe add instruction to disable dashboard on mksession.

**Screenshots**
![gscreenshot_2022-08-23-124421](https://user-images.githubusercontent.com/63652620/186238810-270dc73f-bac2-4e18-8907-16b9dc67d348.png)

**Comment by glepnir** [comment]
I can't reproduce with the dashboard session. can you try the dashboard session ?

**Comment by EpsilonKu** [comment]
I used persisted.nvim with auto-load functionality. Basically it load mksession before ueberzug render it. I guess will be good to add function after_load. Or add auto-load and auto-save.
