### ISSUE TITLE
Open dashboard will start from `insert mode` not `normal mode`

### ISSUE THREAD

**Issue by ckybonist** [glepnir/dashboard-nvim#204]
**Describe the bug**

Open dashboard will start from `insert mode` not `normal mode`.
(current buffer is unmodifiable)

**To Reproduce**

1. Run neovim without file path to open dashboard: `$ nvim`
2. Type any character
3. The error is shown: `E21: Cannot make changes, 'modifiable' is off`

**Expected behavior**

When opening dashboard, the current buffer should start at `normal mode`, so that we don't
need extra `[escape]` to use the dashboard function.

**Screenshots**

![image](https://user-images.githubusercontent.com/3832925/188142085-efc8e3df-86b9-4a8a-bb91-3b0460f853bb.png)

**Comment by glepnir** [comment]
dashboard buffer does not support modified.

**Comment by ckybonist** [comment]
> dashboard buffer does not support modified.

True. 

Could we configure Dashboard to start at `normal mode`?

**Comment by glepnir** [comment]
it's normal mode .I don't change your vim mode . check your config.

**Comment by ckybonist** [comment]
Yeah, my bad. 

I found that the problem is caused by my `preview_command`:

```
cat | lolcat -F 0.3
```
