### ISSUE TITLE
Dashboard doesnt load anything with a standard vim config 

### ISSUE THREAD

**Issue by kavulox** [glepnir/dashboard-nvim#207]
This is what it looks like with the variable g:dashboard_custom_header set to something
![image](https://user-images.githubusercontent.com/108770990/189508792-2064b84e-bf65-4e5b-86e7-ecc20acc26d6.png)
I can echo out the value and it works, but it wont actually load it
![image](https://user-images.githubusercontent.com/108770990/189508847-95c7bb75-2bc0-4b4d-9054-a4866edeb91e.png)
Here is the config I used to test it, I have my own but I wanted to make sure I didnt have anything causing issues: 
![image](https://user-images.githubusercontent.com/108770990/189508863-5107bc9b-3913-404e-99fd-0a7485f5f1ec.png)

**Comment by glepnir** [comment]
you need use lua file or use lua section

```
lua << EOF
local db =require('dashboard')
db.custom_center = {
 your banner
}

EOF

```
