### ISSUE TITLE
Error on startup after installation

### ISSUE THREAD

**Issue by MisustinIvan** [glepnir/dashboard-nvim#208]
So, I installed the plugin, written a basic config(just require('dashboard') {}) and restarted nvim. I get and error on startup, "Error detected while processing VimEnter Autocommands for "*" . It says more things, but even when i zoom out i cant see more. I tried copying other people's configs, even the one from the GitHub page, nothing worked. I dont really know where is the issue, so help would be apreciated.

**Comment by glepnir** [comment]
I am not god. you should post what you do and which config you used.
