### ISSUE TITLE
Ueberzug repeatedly opens on resize

### ISSUE THREAD

**Issue by ThatEpicBanana** [glepnir/dashboard-nvim#209]
**Describe the bug**
When you resize a dashboard window with an ueberzug preview, new ueberzug windows keep getting opened without closing the old ones. 

**To Reproduce**
1. Open a dashboard window with an ueberzug preview
2. Resize the window or set the font in a gui (such as neovide)

**Expected behavior**
The old windows get closed so duplicates don't show up 

**Screenshots**
![image](https://user-images.githubusercontent.com/40611336/190833437-28fabdd2-0d1c-4340-b7e8-50d5f2593f53.png)
I assume the error in the back is x11 getting angry that too many windows are being opened, it started showing up a few seconds after i kept resizing it.

**Comment by ThatEpicBanana** [comment]
I also did some digging in the source, and it seems that `events.lua`

**Comment by ThatEpicBanana** [comment]
That was a mistake sorry

**Comment by ThatEpicBanana** [comment]
This issue seems to also happen in telescope-media-files shown in [this issue](https://github.com/nvim-telescope/telescope-media-files.nvim), so it might be an issue with ueberzug (which I hope it isn't) or a change in neovim that broke things? I don't know

**Comment by glepnir** [comment]
I will take a look at this behavior if I can reproduce it.
