### ISSUE TITLE
Allow having short keybinds for the dashboard buffertype

### ISSUE THREAD

**Issue by MordechaiHadad** [glepnir/dashboard-nvim#211]
**Is your feature request related to a problem? Please describe.**
Basically in https://github.com/startup-nvim/startup.nvim you could have very short keybinds like `q` to quit the editor or `f` to open the file explorer only when you are inside the plugin buffertype, currently it seems like I need to jump through hoops to have any sensible keybinding... for example this is my config currently for dashboard https://hastebin.com/jeqanemuso.lua but any of the keybinds don't really work even though visually everything is fine.

**Describe the solution you'd like**
Well allowing short keybinds for the dashboard buffertype

**Describe alternatives you've considered**
https://github.com/startup-nvim/startup.nvim

**Comment by glepnir** [comment]
yup I already think about this. will implement it .

**Comment by gnsfujiwara** [comment]
> **Is your feature request related to a problem? Please describe.** Basically in https://github.com/startup-nvim/startup.nvim you could have very short keybinds like `q` to quit the editor or `f` to open the file explorer only when you are inside the plugin buffertype, currently it seems like I need to jump through hoops to have any sensible keybinding... for example this is my config currently for dashboard https://hastebin.com/jeqanemuso.lua but any of the keybinds don't really work even though visually everything is fine.
> 
> **Describe the solution you'd like** Well allowing short keybinds for the dashboard buffertype
> 
> **Describe alternatives you've considered** https://github.com/startup-nvim/startup.nvim

You can creata an autocmd for that:
```lua
-- Set keymaps only when dashboard is active
vim.api.nvim_create_autocmd('FileType', {
  group = vim.api.nvim_create_augroup('DashboardMappings', { clear = true }),
  pattern = 'dashboard',
  callback = function()
    vim.keymap.set('n', 'e', '<Cmd>enew<CR>', { buffer = true })
    vim.keymap.set('n', 'q', '<Cmd>q!<CR>', { buffer = true })
  end,
})
```
