### ISSUE TITLE
unknown option 'winbar '

### ISSUE THREAD

**Issue by jinzhongjia** [glepnir/dashboard-nvim#214]
**Describe the bug**
I just updated the new version, and then there was an error. After my investigation, it should be caused by this push https://github.com/glepnir/dashboard-nvim/commit/8f5b3996ec99e53af8c78a8a238a571604a95d96

**Screenshots**

![image](https://user-images.githubusercontent.com/41784264/193233412-59a4e25c-2d9b-4349-ad51-a26d5d6c24a7.png)

**version**

```bash
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/8svf52rgypxxjcwq5l1sjcykmibb7a61-neovim-unwrapped-0.7.2/share/nvim
"
```

**Comment by glepnir** [comment]
oh ..because the winbar is 0.8 option. it will release a few later

**Comment by jinzhongjia** [comment]
> oh ..because the winbar is 0.8 option. it will release a few later

em... the neovim in nixos's unstable pkgs is 0.7.2 
Maybe I need to live with this error for a while
