### ISSUE TITLE
session opt-out and named sessions

### ISSUE THREAD

**Issue by rebelot** [glepnir/dashboard-nvim#217]
Hi, thanks for your plugin :)

I have some suggestions for session feature:

1) make session support opt-out: if I am using another plugin to manage sessions, I don't want duplicate functionality. So an option to disable creation of session command/functionality would be nice.

2) support named sessions. Example:

```vim
:SessionSave my_session
:SessionLoad my_session
```

3) default session directory to: `vim.fn.stdpath('data') .. '/sessions'`

**Comment by glepnir** [comment]
sounds reasonable
