### ISSUE TITLE
Newfile

### ISSUE THREAD

**Issue by notwidow** [glepnir/dashboard-nvim#221]
HI, one small request is to make the dashboard feature of making newfile more advanced.

For example....
If i want to create a new file from dashboard and i press enter on it. then before opening the empty file it should ask about the file name. like when selected then a small window popup should appear asking for the file name. In this way we wont be needed to save the file in order for syntax-highlighting and more.
Additionally
It would also be great if it becomes able to create directorys or subdirectorys for the file also. like if in the popup window when it asks for file example/lua.lua is given the it should check the exmaple directory in the current directory and if it does not exists then it can create the directory as well with new file (with specified name)..... THANKS~~~!!!

**Comment by RAprogramm** [comment]
Perfect idea!

**Comment by RAprogramm** [comment]
```
local Input = require('nui.input')
local event = require('nui.utils.autocmd').event

_G.dashNewFile = Input({
  position = '50%',
  size = {
    width = 40,
  },
  border = {
    style = 'rounded',
    text = {
      top = ' Create a new file ',
      top_align = 'center',
    },
    padding = { 0, 1 },
  },
  relative = 'editor',
  win_options = {
    winhighlight = 'Normal:String,FloatBorder:VertSplit',
  },
}, {
  prompt = '',
  default_value = '',
  on_close = function()
    require('notify').notify('New file was not created!', 'error')
  end,
  on_submit = function(value)
    vim.fn.execute('DashboardNewFile')
    vim.fn.execute('w ' .. value)
  end,
})
dashNewFile:on(event.BufLeave, function() inputMod:unmount() end)
```
in vim command-mode `lua dashNewFile:mount()`  to run
i bind this with which-key `:lua dashNewFile:mount()<CR>`
