### ISSUE TITLE
Color highlights not working

### ISSUE THREAD

**Issue by As2aic** [glepnir/dashboard-nvim#226]
I installed and configured dashboard. but I cannot understand why color highlighting is not working? Like for commands (new file,history, config) one color and for strings and shortcuts another color. In my case everything is white.
 
![color_issue_dashboard_nvim](https://user-images.githubusercontent.com/87420375/199388015-1b593ef1-b63c-49d0-b5e1-f2f720ee4fc3.png)
the configuration,
`db.default_banner = {
  '',
  '',
 ' ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗',
 ' ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║',
 ' ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║',
 ' ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║',
 ' ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║',
 ' ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝',
  '',
  ' [ Dashboard version 0.2.2 ] ',
  '',
}
db.custom_header = nil
db.custom_footer = {"Life is what happens when you're busy making other plans. - John Lanon"}
db.custom_center = {
  { icon = '', desc = ' New File', action = 'DashboardNewFile' },
  { icon = '', desc = ' Find File', action = 'Telescope find_files' },
  { icon = '   ', desc = ' Recent Files', action = 'Telescope oldfiles' },
  { icon = '   ', desc = ' Search Text', action = 'Telescope live_grep' },
  { icon = '     ', desc = ' Configuration', action = 'edit /home/msbis/.local/share/nvim/site/pack/packer/start/dashboard-nvim/lua/dashboard/init.lua' }
}

db.preview_file_Path = nil
db.preview_file_height = 0
db.preview_file_width = 0
db.preview_command = ''
db.image_width_pixel = 0
db.image_height_pixel = 0
db.hide_statusline = true
db.hide_tabline = true
db.hide_winbar = true
db.session_directory = ''
db.session_auto_save_on_exit = false
db.session_verbose = true
db.header_pad = 1
db.center_pad = 1
db.footer_pad = 1
db.disable_at_vimenter = false
`

**Comment by glepnir** [comment]
all the highlight groups in readme. find them then set them like 

```
hi DashboardHeader guifg=xxxx
``
