### ISSUE TITLE
Error on several consequtive Dashboard commands

### ISSUE THREAD

**Issue by illia-danko** [glepnir/dashboard-nvim#227]
**Describe the bug**
Dashboard command produces an error on the second consequent `:Dashboard<cr>` command execution when another buffer is opened.

**To Reproduce**
Open nvim and initial Dashboard buffer is loaded
1. Visit a file: `:e anyfile<cr>`
2. Summon Dashboard `:Dashbaord<cr>`
3. Summon Dashboard `:Dashbaord<cr>`

**Expected behavior**
On any consecutive execution `:Dashboard<cr>` no error expected

**Actual behavior**
On the second Dashboard command (step 3 above) error occurred:
```lua
Error executing Lua callback: .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:114: Invalid buffer id: 7
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:114: in function 'set_line_with_highlight'
        .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:399: in function 'load_from_cache'
        .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:472: in function 'instance'
        ...te/pack/packer/start/dashboard-nvim/plugin/dashboard.lua:53: in function <...te/pack/packer/start/dashboard-nvim/plugin/dashboard.lua:52>
```

**Comment by glepnir** [comment]
I will take a look at this later.
