### ISSUE TITLE
Does the footer support text return from a function?

### ISSUE THREAD

**Issue by omegahh** [glepnir/dashboard-nvim#228]
I want to make the footer show the tips from a cheatsheet or TODO things. I think if the footer content could be a return value of function, then I can write a custom function which return a string according to my prefer. 

For example, If I pre-defined some tips of vim operation, and a function will return one of them randomly. Thus my dashboard's footer could show random tips if it supports.

**Comment by glepnir** [comment]
can be support.

**Comment by omegahh** [comment]
Oh, I know. It possibly is a Lua question, considering that I didn't use Lua before. But the answer is clear for me now maybe. I will try. Thank you for replying!
