### ISSUE TITLE
prevent dashboard auto close for some filetypes

### ISSUE THREAD

**Issue by YuCao16** [glepnir/dashboard-nvim#229]
**Is your feature request related to a problem? Please describe.**
I remember that from a certain version,  dashboard-nvim started to close automatically (something like WinEnter), so that if I use `PackerUpdate` after entering nvim, the dashboard will close. 

At first this was fine, but now I switched from `nvim-tree` to `neo-tree`, and every time I enter `nvim` and then toggle `neotree`, the dashboard will close and looks a bit strange... :

**Describe the solution you'd like**
I wish the automatic closing of the dashboard could be set to except for `neo-tree` or packer etc.

**Describe alternatives you've considered**
Nothing.

**Additional context**
`neo-tree`:
<img width="1548" alt="iShot_2022-12-05_12 02 00" src="https://user-images.githubusercontent.com/62466929/205632798-622cd945-3e12-41d7-9556-2c150bf829c6.png">
`nvim-tree`:
<img width="1548" alt="iShot_2022-12-05_12 01 52" src="https://user-images.githubusercontent.com/62466929/205632812-18ab6540-a61e-4878-8a6e-3c6557e15693.png">

**Comment by glepnir** [comment]
there need a refactor and I try to make a new theme :) maybe we can fix this.

**Comment by RAprogramm** [comment]
have any idea how to fix this for neo-tree?

**Comment by RAprogramm** [comment]
[Screencast_00000.webm](https://user-images.githubusercontent.com/70325462/210510475-bf82fb98-8ed2-4a22-bcd4-f16616f3cfd3.webm)

**Comment by YuCao16** [comment]
It would be easier by comment out these lines:
https://github.com/glepnir/dashboard-nvim/blob/e517188dab55493fb9034b4d4f1a508ccacfcd45/lua/dashboard/events.lua#L37-L39

**Comment by YuCao16** [comment]
> > > have any idea how to fix this for neo-tree? i noticed that if you enter in command-mode (press ":") after you enter the vim and see a dashboard, and the exit from command-mode (press ) all works good
> > > Screencast_00000.webm
> > > if you not entered in command-mode before open neo-tree - you will see empty page after close neo-tree
> > 
> > 
> > It would be easier by comment out these lines:
> > https://github.com/glepnir/dashboard-nvim/blob/e517188dab55493fb9034b4d4f1a508ccacfcd45/lua/dashboard/events.lua#L37-L39
> 
> In this lines neo-tree looks "NeoTree". As I know must be "neo-tree".

I tried to correct this but got errors. So since comment out those lines works, I didn't dig it deeper :D

**Comment by RAprogramm** [comment]
It is comment loop))

**Comment by glepnir** [comment]
code of there a little stupid . use `nvim_list_wins` to get winid then get buffers and do some check would be better not use filetype.
