### ISSUE TITLE
I made this because I missed vim-startify's quotes

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [glepnir/dashboard-nvim#23]
Hey dashboard-nvim is really awesome! I missed vim-startify's random quote every time I opened vim. So I made [this](https://github.com/Th3Whit3Wolf/pquote), it has 323 programmer quotes (vim-startify is around 146 I think). It's a binary, so it won't effect load time or performance, with releases for linux, mac, and windows.

In case anyone reads this all you have to do to use it is 

* Dowload a release and move the binary into path or build it from source
* Add the this to either `init.vim`/`.vimrc` or `after/plugin/dashboard.vim`
```viml
let q= systemlist('pq')
let g:dashboard_custom_footer = q
```

**Comment by glepnir** [comment]
Seems like pretty good. I  will give it a try.

**Comment by Th3Whit3Wolf** [comment]
Awesome, let me know if there is anything you think that could be improved upon.
