### ISSUE TITLE
Buffer number grows exponentially on resizing neovim.

### ISSUE THREAD

**Issue by Matias-Hall** [glepnir/dashboard-nvim#231]
**Describe the bug**
Every time neovim is resized the buffer number of the dashboard window is multiplied by 2 (1 to 2, 2 to 4, 4 to 8, etc). Using :ls! shows no extra buffers are created, only the buffer number changes.

**To Reproduce**
1. Open nvim with no arguments (so that the dashboard opens).
2. Resize the nvim window. For example, by using :set columns=<num>
3. Use :ls! to see the new buffer number.
4. Repeat steps 2 and 3, watching the number grow.

**Expected behavior**
The buffer number shouldn't change (the same buffer should be used), or at least it should grow linearly, not exponentially.

**Comment by glepnir** [comment]
reproduce.
