### ISSUE TITLE
Telescope man_pages buffer error

### ISSUE THREAD

**Issue by nemo256** [glepnir/dashboard-nvim#233]
**Describe the bug**
`:Telescope man_pages` command shows a no buffer error only on dashboard initial screen.

**To Reproduce**
1. `:Telescope man_pages`  # on start screen

**Expected behavior**
Show the manpage without the **invalid buffer id error**.

**Screenshots**
![man_pages_error](https://user-images.githubusercontent.com/53398332/210454915-54ad5762-5c12-4ff4-ad22-441ebe6740f0.png)

**Comment by nemo256** [comment]
_UPDATE:_ when I list out all my keymaps i found this dashboard keymap:
n  <CR>        *@<Cmd>lua require("dashboard").call_line_action()<CR>
And whenever I click on Enter it seems to execute `:Telescope man_pages`.

**Comment by nemo256** [comment]
Here is my init.lua config:
`
local home = os.getenv('HOME')
local db = require('dashboard')

-- Dashboard config
db.custom_header = {
    '          ▀████▀▄▄              ▄█ ',
    '            █▀    ▀▀▄▄▄▄▄    ▄▄▀▀█ ',
    '    ▄        █          ▀▀▀▀▄  ▄▀  ',
    '   ▄▀ ▀▄      ▀▄              ▀▄▀  ',
    '  ▄▀    █     █▀   ▄█▀▄      ▄█    ',
    '  ▀▄     ▀▄  █     ▀██▀     ██▄█   ',
    '   ▀▄    ▄▀ █   ▄██▄   ▄  ▄  ▀▀ █  ',
    '    █  ▄▀  █    ▀██▀    ▀▀ ▀▀  ▄▀  ',
    '   █   █  █      ▄▄           ▄▀   ',
    '                                   ',
}
db.custom_center = {
  {icon = '  ',
  desc = 'Recently opened files                   ',
  action =  'Telescope oldfiles',
  shortcut = '<CTRL + H>'},
  {icon = '  ',
  desc = 'Find File                               ',
  action = 'Telescope find_files find_command=rg,--files',
  shortcut = '<CTRL + F>'},
  {icon = '  ',
  desc = 'Load Session                            ',
  action =  'SessionLoad',
  shortcut = '<CTRL + L>'},
  {icon = '  ',
  desc = 'Open Projects                           ',
  action = 'e ~/Work',
  shortcut = '<CTRL + W>'},
}
db.custom_footer = {}

db.hide_statusline = true
db.hide_tabline = true
db.hide_winbar = true
db.session_directory = '~/.config/nvim/session'
db.session_auto_save_on_exit = true
db.session_verbose = true
`

**Comment by glepnir** [comment]
I can't reproduce update your telescope then test.

**Comment by nemo256** [comment]
> _UPDATE:_ when I list out all my keymaps i found this dashboard keymap: `n <CR> *@<Cmd>lua require("dashboard").call_line_action()<CR>` And whenever I click on Enter it seems to execute `:Telescope man_pages`.

This is fixed, it was the <C-m> triggering <CR>, remaping to a different keybindings fixes it.





> I can't reproduce update your telescope then test.

I tried reinstalling both telescope and dashboard, only by removing dashboard the issue does not occur, the telescope manpages command doesn't work only on the dashboard splash screen.

**Comment by nemo256** [comment]
I also tried a minimal version with only telescope and dashboard installed, problem is still present.
Here is the init.lua to reproduce:

```
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function(use)
	use 'wbthomason/packer.nvim'

	-- Dashboard
	use 'glepnir/dashboard-nvim'

	-- Telescope
	use {
		'nvim-telescope/telescope.nvim', tag = '0.1.0',
		requires = { {'nvim-lua/plenary.nvim'} },
		require("telescope").setup()
	}
end)
```
