### ISSUE TITLE
Invisible cursor after load saved session

### ISSUE THREAD

**Issue by RAprogramm** [glepnir/dashboard-nvim#234]
[Screencast_00003.webm](https://user-images.githubusercontent.com/70325462/210485054-9bba8ce7-efc8-43a1-b35c-5e27231da7e2.webm)

**Comment by RAprogramm** [comment]
```
 db.session_auto_save_on_exit = true
 db.session_directory = vim.fn.stdpath('cache') .. '/session'
 db.session_verbose = true

 vim.api.nvim_create_autocmd('User', {
   pattern = 'DBSessionSavePre',
   callback = function() vim.cmd('NeoTreeClose') end,
 })
```
all good after adding this code

**Comment by glepnir** [comment]
hmm I don't think it's caused by dashoard.  it's a plugin in neovim . I don't we can handle cursor ..

**Comment by RAprogramm** [comment]
don't you think that it happens because load session?

**Comment by glepnir** [comment]
no. can't reproduce.

**Comment by RAprogramm** [comment]
ok, i got you! thank you!
