### ISSUE TITLE
Reversed keybinds: go to top, go to bottom

### ISSUE THREAD

**Issue by diegoulloao** [glepnir/dashboard-nvim#236]
**Describe the bug**
When I press `gg` the cursor goes to the bottom and not the top. Contrary, `G` goes to the top instead the bottom.

**To Reproduce**
1. Press `gg`
2. Press `G`

**Expected behavior**
Go to the top when pressing `gg`, and bottom when `G`

**Screenshots**

https://user-images.githubusercontent.com/45423661/211225462-60c14a09-1dc2-4cba-bbf7-c7f36411d12c.mp4

**Comment by glepnir** [comment]
this is expected behavior . because dahsboard handle the cursor move in this buffer.

**Comment by diegoulloao** [comment]
but is reversed, is okay if the dashboard is controlling the keybindings but it shouldn't contradict the vim standard of movements. In vim `gg` is used to go to the top and `G` to go to the bottom. Dashboard should follow the same directive.

**Comment by glepnir** [comment]
.nope. control the cursor move.not keymap binding
