### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by rsignavong** [glepnir/dashboard-nvim#237]
**Describe the bug**
Just after a PackerSync, I got an error. It worked fine just before.

**To Reproduce**
I don't have any custom configuration yet, it's my first usage of dashboard-nvim.
I just wanted to add some configuration but after a PackerSync, I have just launched neovim and it throws an error now.

**Expected behavior**
No error

**Screenshots**
Error detected while processing VimEnter Autocommands for "*":
Error executing lua callback: vim/_meta.lua:0: no such option: 'stc'
stack traceback:
        [C]: in function 'nvim_get_option_info'
        vim/_meta.lua: in function '__index'
        vim/_meta.lua: in function ''
        vim/_meta.lua: in function '__newindex'
        .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:73: in function 'set_buf_local_options'
        .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:475: in function 'instance'
        ...te/pack/packer/start/dashboard-nvim/plugin/dashboard.lua:12: in function <...te/pack/packer/start/dashboard-nvim/plugin/dashboard.lua:10>
<img width="1439" alt="Screenshot 2023-01-10 at 11 23 46" src="https://user-images.githubusercontent.com/665533/211525815-06abc723-95fe-444f-a8df-c1955a96d5f8.png">

**Comment by fecet** [comment]
Same issue even after https://github.com/glepnir/dashboard-nvim/commit/b87cb0918e019f7e3981fdb671221bc9851b299a

**Comment by rsignavong** [comment]
yes after a `PackerUpdate` to fetch your commit [b87cb09](https://github.com/glepnir/dashboard-nvim/commit/b87cb0918e019f7e3981fdb671221bc9851b299a) the issue is still there

**Comment by glepnir** [comment]
update

**Comment by glepnir** [comment]
update

**Comment by rsignavong** [comment]
It's working fine now! 👍

**Comment by fecet** [comment]
nvim 0.8.0 now works but it seems that 0.9.0 still breaks

**Comment by glepnir** [comment]
works fine for me on 0.9

**Comment by Coien-rr** [comment]
> Same issue even after [b87cb09](https://github.com/glepnir/dashboard-nvim/commit/b87cb0918e019f7e3981fdb671221bc9851b299a)

maybe you can set commit to https://github.com/glepnir/dashboard-nvim/commit/e517188dab55493fb9034b4d4f1a508ccacfcd45 to avoid this problem for now

**Comment by Coien-rr** [comment]
> Same issue even after [b87cb09](https://github.com/glepnir/dashboard-nvim/commit/b87cb0918e019f7e3981fdb671221bc9851b299a)

@fecet maybe you can set commit to https://github.com/glepnir/dashboard-nvim/commit/e517188dab55493fb9034b4d4f1a508ccacfcd45 to avoid this problem for now

**Comment by glepnir** [comment]
why set commit ? it had fixed

**Comment by Coien-rr** [comment]
> why set commit ? it had fixed
I have updated neovim and dashboard but this problem still 😭
neovim version is 0.9

**Comment by calvinchoy** [comment]
Make sure you are using the latest neovim nightly of 0.9. I had the same issue and update my nvim 0.9-dev to latest and all working fine again.

**Comment by marcomayer** [comment]
I get the same error on nvim commit 99cf111289bfcd14981255e805da43bac5139141. I'm hanging out there because there's an issue with noice.nvim breaking after this commit. So hopefully one of the two will get fixed 😆

**Comment by Coien-rr** [comment]
after update to the lastest neovim uploaded by _ppa:neovim-ppa/unstable_, dashboard working fine again!
