### ISSUE TITLE
can not open file

### ISSUE THREAD

**Issue by accyzxin** [glepnir/dashboard-nvim#242]
**Describe the bug**

system: windows 10
neovim version: v0.8.2

```
E5108: Error executing lua: ...acker\start\dashboard-nvim/lua/dashboard/theme/hyper.lua:159: attempt to index local 'stat' (a nil value)
```

**To Reproduce**
1. use packer install dashboard-nvim
2. create dashboard.lua config file
3. add to init.lua

**Expected behavior**
open the file to see if the configuration is successful

**Screenshots**
![image](https://user-images.githubusercontent.com/64626594/214585620-b9ac181c-35f1-4780-ad2e-80ae134fdde2.png)
![image](https://user-images.githubusercontent.com/64626594/214585710-aca89660-2f01-455d-91b3-462086685bc9.png)
![image](https://user-images.githubusercontent.com/64626594/214585763-8c84f94e-5191-4619-9575-e53afcc29c54.png)
![image](https://user-images.githubusercontent.com/64626594/214586160-cddc9504-eb40-4806-a67e-cdff3da1e985.png)

**Comment by glepnir** [comment]
then you see the file list in.most rencent files section and press a.key to open right?

**Comment by badloop** [comment]
Same issue here but in different areas using the doom theme.  From what I can tell the theme configs seem to be assuming that certain things will be set up in the config but no sane default has been provided.  I too have a very minimal config with only a header defined.  I've been able to bypass some of the errors I've been getting by adding sections to my setup, but it shouldn't be necessary.

**Comment by fecet** [comment]
I still have the same problem

**Comment by glepnir** [comment]
Windows file path is what

**Comment by badloop** [comment]
Seems like there is still an issue for doom but hyper is working again.

**Comment by glepnir** [comment]
doom does not have open item ? please provide your config./

**Comment by glepnir** [comment]
maybe need real path of fame escape ? but I had convert it to true path in someweher

**Comment by 1538379200** [comment]
use the ```os.getenv("USERPROFILE")``` can get the user directory,replace the ```~``` ,Windows dont know the ```~``` 
![image](https://user-images.githubusercontent.com/42434762/215932089-7b251f59-f21a-4034-bc52-a56eaaa0698d.png)

**Comment by glepnir** [comment]
the latest version i didn't replace the home to～ in Windows . wired

**Comment by 1538379200** [comment]
final version:
runs on linux and Windows
![image](https://user-images.githubusercontent.com/42434762/215940671-27b525eb-ea67-4df0-b5b8-14e06a94c74b.png)

**Comment by 1538379200** [comment]
this is final
only Windows
![image](https://user-images.githubusercontent.com/42434762/215941621-c3f42e2d-fb77-4c0e-89a9-7a427beee060.png)

**Comment by glepnir** [comment]
problem is why a win path will have `~` i did not conver the `C:\\Users` to  `~`.

**Comment by 1538379200** [comment]
if ```~``` in Windows PowerShell,```~``` can be recognized.
Maybe nvim conver ```C:\Users\<user>``` to ```~```.
If dashboard is going to work on linux, Windows and macOS, you may need to use some judgment.

**Comment by glepnir** [comment]
there has util.iswin . i know nothing about win env T>T

**Comment by 1538379200** [comment]
The operating system can be identified with vimscript, but not with lua.
vimscript:
```vimscript
if has("win32") || has("win64") || has("win16"):
    " Windows configuration
else:
    " linux or macOS configuration
endif
```
I found your video on bilibili, so I chose to try the dashboard

**Comment by glepnir** [comment]
what i mean is i already do check and not replace the home to `~` if in windows.

https://github.com/glepnir/dashboard-nvim/blob/658572de910b109bbb9e1c0ed1da38694fab591a/lua/dashboard/theme/hyper.lua#L141-L145

**Comment by 1538379200** [comment]
emmm……
I rarely use lua.
Maybe you don't have to convert? i dont know.

**Comment by 1538379200** [comment]
Another solution:
If it is because util.is_win does not take effect, you can comment the line above Win.

- Get rid of lines 141 to 143
![image](https://user-images.githubusercontent.com/42434762/216029893-e1ecefe7-c3d0-4c19-a6db-1e585b19a303.png)

- Replace "%p" in line 177 with "%w"
![image](https://user-images.githubusercontent.com/42434762/216030026-ee281d9a-adf3-4a53-891c-784c355c6afd.png)

**Comment by P1P0S** [comment]
@1538379200 Even after changing "%p" to "%w", I still had problems with the directories:
![image](https://user-images.githubusercontent.com/62353660/216115730-61d3573c-f35c-4979-a11f-d0c5e0d38425.png)

What worked for me was to comment out this check which always returns 'nil':
![image](https://user-images.githubusercontent.com/62353660/216114342-2c9dc231-c779-4eb8-a95c-7afc6601b6ce.png)

**Comment by 1538379200** [comment]
@P1P0S 
### if win:
- You need to comment out 141 to 143 because this will convert the Win User directory to ```~```
- Window doesn't need ```~``` to tell if it's a directory, so we replace ```%p``` with ```%w``` on line 177
- You don't need to change any other Settings
