### ISSUE TITLE
Letters for open a file/project at the left side (hyper theme)

### ISSUE THREAD

**Issue by diegoulloao** [glepnir/dashboard-nvim#245]
**Is your feature request related to a problem? Please describe.**
Not a problem. I think letters at the right for open a file looks weird.

**Describe the solution you'd like**
Letters beside the icons would look better.

🕙 Most recent projects:
[v] 📂  ~/projects/dashboard-nvim
[h] 📂  ~/projects/lspsaga.nvim

🕙 Most recent files:
[l] 📄 ~/projects/dashboard-nvim/lua/init.lua
[k] 📄 ~/projects/lspsaga.nvim/lua/init.lua

**Comment by glepnir** [comment]
This only works somewhat for short strings. But when your filename is very long. The shortcut is not ergonomic at the front. The glasses gaze on the right side of the screen when your eyes see the filename. So you can capture the shortcut for this line. If the path is short in front of you you can catch them with both eyes. But this is a bit weird when the path is long.

I just add a highlight group for them to make them color support custom. then you can link to comment .you may feel better.

another way is not fill space at the end of string . then put the shorcut at that. will  better . but the ui will look wired.
