### ISSUE TITLE
Lualine not visible when opening a file in Telescope from Dashboard buffer

### ISSUE THREAD

**Issue by diegoulloao** [glepnir/dashboard-nvim#246]
**Describe the bug**
When I'm in the dashboard and I search for a file in Telescope to open in tab mode, lualine disappears.
I deactivated the Dashboard plugin and all works normally.

**To Reproduce**
1. Open nvim in order to see the dashboard
2. Find a file in Telescope
3. Open it in tab mode

**Current behavior**
Lualine disappears

**Expected behavior**
See lualine as always

**Screenshots**
1. I'm opening the file in normal mode (pressing enter)
2. I'm opening the file in tab mode (ctrl-t)

https://user-images.githubusercontent.com/45423661/214743598-6f59bbe8-0d9d-468c-b915-a90542ed0d79.mov

**Comment by glepnir** [comment]
hide.statusline =false

**Comment by diegoulloao** [comment]
Ok, that fixes the issue when opening the file in a tab but now the problem is that lualine is displayed in the dashboard.

The entire solution is:

`dashboard`
```lua
require("dashboard").setup({
  ...
  hide = {
    statusline = false
  }
})
```

`lualine`
```lua
require("lualine").setup({
  ...,
  options = {
    disabled_filetypes = { ..., "dashboard" }
  }
})
```

Hope it be useful.

**Comment by glepnir** [comment]
it load after ？dashboard

**Comment by diegoulloao** [comment]
https://github.com/diegoulloao/nvim-diegoulloao/blob/b105dfcd5e7c6568759ec1c97f4226a8604fdbdf/bootstrap.lua#L31

lualine:13
dashboard:31

dashboard is loaded after lualine

**Comment by glepnir** [comment]
this is config load order ? I mean the plugin load. how do you load dashboard and lualine

**Comment by diegoulloao** [comment]
> this is config load order ? I mean the plugin load. how do you load dashboard and lualine

Yes that's the order, is a bootstrap file that is required into my `init.lua` file.
All my config is in that repository.

These are the config files:

`lualine`
https://github.com/diegoulloao/nvim-diegoulloao/blob/b648d10fe53e811d8289a94c81584a927bc43838/plugins/lualine.lua#L56

`dashboard`
https://github.com/diegoulloao/nvim-diegoulloao/blob/9f4655f85e6a8cdf36be5957985e0376b5e653b7/plugins/dashboard.lua#L16

**Comment by glepnir** [comment]
use event to lazyload dashboard.
