### ISSUE TITLE
attempt to concatenate local 'icon' when using Hyper theme with default configs

### ISSUE THREAD

**Issue by karunsiri** [glepnir/dashboard-nvim#247]
**Describe the bug**
Just updated the plugin to this commit 1af4b737668012ba3af90c909df121eb003170b8 with provided example configurations 

```lua
db.setup({
  theme = 'hyper',
  config = {
    shortcut = {
      { desc = ' Update', group = 'DashboardShortCut', action = 'PackerSync', key = 'u' },
    },
  },
})
```

When opening a new nvim instance by executing

    nvim

The error occurs
![dashboard no mru list](https://user-images.githubusercontent.com/1308495/214752553-da008947-6cbd-4130-b56e-55b22a37634a.png)

Raw log for future reference
```txt
hyper.lua:123: attempt to concatena
te local 'icon' (a nil value)
stack traceback:
        dashboard-nvim/lua/dashboard/theme/hyper.lua:123: in function 'mru_list'
        dashboard-nvim/lua/dashboard/theme/hyper.lua:171: in function 'gen_center'
        dashboard-nvim/lua/dashboard/theme/hyper.lua:272: in function 'callback'
       dashboard-nvim/lua/dashboard/theme/hyper.lua:100: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**To Reproduce**
1. Set up dashboard-nvim using Hyper theme with example configuration
2. Open new instance of nvim

**Expected behavior**
Nvim starts with dashboard shown without errors

**Screenshots**
![dashboard no mru list](https://user-images.githubusercontent.com/1308495/214752747-cca4c4b8-46dc-46f4-8b3f-72daa320c985.png)

**Comment by karunsiri** [comment]
Though I find these lines and not sure if it's the cause of this or not. https://github.com/glepnir/dashboard-nvim/blob/master/lua/dashboard/utils.lua#L87-L93

I do have nvim-web-devicons installed, but this is the first time I run the new dashboard so my MRU list would be `nil`?
I don't know lua so please have a look.

Thank you!

**Comment by glepnir** [comment]
> I do have nvim-web-devicons installed, but this is the first time I run the new dashboard so my MRU list would be nil?

nope it will read `v:old` . if it is empty I will fill a empty message
