### ISSUE TITLE
Possibility to use function instead of string in `action` property for `shortcut` field.

### ISSUE THREAD

**Issue by Flo-Slv** [glepnir/dashboard-nvim#250]
**Is your feature request related to a problem? Please describe.**
Hey, I am trying to implement that functionality to the `Hyper` theme.

![packer dashboard](https://user-images.githubusercontent.com/11678456/214876636-e2d1db4a-fb09-4cbf-ae85-8fa79c33edbf.png)

But I got this error.

![dashboard error](https://user-images.githubusercontent.com/11678456/214876854-0645d12c-0b7b-4fa3-8529-0f2c52c29d81.png)

**Describe the solution you'd like**
Is it possible to implement of function instead of a string in `shortcut` field for `action` property ?

**Describe alternatives you've considered**

**Additional context**

**Comment by mariomttz** [comment]
Hello friend, hey a question, how did you do to put the date in the footer?

**Comment by mathjiajia** [comment]
> Hello friend, hey a question, how did you do to put the date in the footer?

Use this lua function `os.date()`?

**Comment by Flo-Slv** [comment]
> Hello friend, hey a question, how did you do to put the date in the footer?

Hey

In lua you can use `os.date("%A %d/%m/%Y %H:%M")`

**Comment by Flo-Slv** [comment]
@glepnir  thanks for the possibility to add function in `action`.

I am sorry to bother you again :/ Now I have an other error.

I can use function as you can see in the next two screenshots

![dashboard](https://user-images.githubusercontent.com/11678456/215038756-290abe9b-784c-46a8-a2fb-cbb641091cf8.png)

![dashboard 2](https://user-images.githubusercontent.com/11678456/215038771-aa228aec-cffb-4eff-8108-85f2eb90b9a1.png)

Then I got this error

![dashboard error](https://user-images.githubusercontent.com/11678456/215038845-a11e7e1d-f829-4eda-811d-bdf5308000ca.png)

Any ideas ?

Thanks !

**Comment by glepnir** [comment]
hmm because it's a function type then it can not write into cache by using json.encode ..

**Comment by glepnir** [comment]
maybe need dump it first then encode the binary data into json ...let me try it later.

**Comment by Flo-Slv** [comment]
> maybe need dump it first then encode the binary data into json ...let me try it later.

Okey ! I get it. Thanks !

You rocks !

**Comment by glepnir** [comment]
update . should be works .

**Comment by Flo-Slv** [comment]
> update . should be works .

It's working great ! thanks

Next step, dashboard.nvim should be able to make my coffee xD

Good job !
