### ISSUE TITLE
Error when starting with NVIM - Invalid (empty) LHS

### ISSUE THREAD

**Issue by kaufmajo** [glepnir/dashboard-nvim#251]
**Describe the bug**
I updated the plugin ... Packer installed/updated the plugin, but since then this error appears when i start nvim with the dashboard.

I am using Neovim 8.2 on Debian Bullyseye on WSL2 and the Windows Terminal

![grafik](https://user-images.githubusercontent.com/25032826/214881130-be4779ce-7ce3-4eea-97d7-29f71e1f4e05.png)

This is my config:

plugins.lua ->

`
use({
    'glepnir/dashboard-nvim',
    event = 'VimEnter',
    config = function()
        require('user.plugins.dashboard')
    end,
    require = {{'nvim-tree/nvim-web-devicons'}}
})
`

dashboard.lua ->

`require('dashboard').setup({
    theme = 'doom',
    config = {
        header = {},
        center = {{
            icon = '  ',
            desc = 'New file',
            key = '',
            action = 'enew'
        }, {
            icon = '  ',
            desc = 'Find file',
            key = 'SPC f',
            action = 'Telescope find_files'
        }, {
            icon = '  ',
            desc = 'Recent files',
            key = 'SPC h',
            action = 'Telescope oldfiles'
        }, {
            icon = '  ',
            desc = 'Find Word',
            key = 'SPC g',
            action = 'Telescope live_grep'
        }},
        footer = {}
    }
})`

**Comment by kaufmajo** [comment]
I Updated to the latest nightly release, but the error is still the same:

![grafik](https://user-images.githubusercontent.com/25032826/214894329-b9a44071-b256-4349-b566-3ca9a9286f72.png)

**Comment by glepnir** [comment]
key is a key map of this buffer not your keymap spc xxx. just a letter.

**Comment by kaufmajo** [comment]
May I ask you to give me a hint what I can do to solve this? Unfortunately I am new to neovim, lua and doesn't understand this kind of error.

**Comment by glepnir** [comment]
`center = {{ icon = '  ', desc = 'New file', key = 's', action = 'enew' },` key just a letter

**Comment by Flo-Slv** [comment]
> May I ask you to give me a hint what I can do to solve this? Unfortunately I am new to neovim, lua and doesn't understand this kind of error.

I think you have to use `f` instead of `SPC f`.

**Comment by kaufmajo** [comment]
Sorry I took up your time. Adjusted my config and now it runs perfectly. Thank you very much for the help.
