### ISSUE TITLE
hyper主题 project区域可以自定义图标吗

### ISSUE THREAD

**Issue by HUAHUAI23** [glepnir/dashboard-nvim#253]
大兄弟 这一块内容可以自定义吗  project 和recent file 前面的图标可以修改吗，还有 sharp tool 哪里可以自己定义或者去除掉吗。

![image](https://user-images.githubusercontent.com/43649186/214984339-7f51d6aa-d2f7-4686-824a-600488ae0e6c.png)

**Comment by glepnir** [comment]
please english in github

**Comment by glepnir** [comment]
`sharp tool ` is footer. icon not support  custom yet. will add it later.

**Comment by HUAHUAI23** [comment]
> please english in github

呃呃 大兄弟咱都是国人，整啥洋文啊😅

**Comment by glepnir** [comment]
只有你用github吗？ 任何遇到问题都是先搜索issue 懂？ 有用的issue 会帮助其他人减少给开源作者带来麻烦？ 我没那么多时间处理重复的issue 。不会github去学学？
