### ISSUE TITLE
case

### ISSUE THREAD

**Issue by glepnir** [glepnir/dashboard-nvim#254]
![image](https://user-images.githubusercontent.com/41671631/215013525-58aba397-03f8-4f48-8af7-ecf7f3134de9.png)

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/215015845-b13343c4-427e-45d6-9f92-267ab909eff1.png)

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/215015845-b13343c4-427e-45d6-9f92-267ab909eff1.png)

**Comment by HUAHUAI23** [comment]
农历好评 ！！！
