### ISSUE TITLE
The plugin stopped working after one of the updates

### ISSUE THREAD

**Issue by smileart** [glepnir/dashboard-nvim#258]
**Describe the bug**
A few days ago, there was update for [dashboard-nvim](https://github.com/glepnir/dashboard-nvim) and since then the dashboard is not working. Currently I have the very latest version from ~10 min ago, but still on opening nvim or calling `:Dashboard` I get either an empty `[Scratch]` buffer or a standard splash screen. Didn't change config or anything at all, so no idea how to debug or reproduce. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open `:Dashboard` or open a new `nvim`

**Expected behaviour**
Expect to see the dashboard I've always had

**Screenshots**
<img width="533" alt="image" src="https://user-images.githubusercontent.com/455338/215036870-3dad97ba-2cec-4bfc-8d0a-6d46bdbc5306.png">

**Comment by glepnir** [comment]
please see doc

**Comment by smileart** [comment]
Perhaps if changes are breaking and totally incompatible with the previous versions, it makes sense to make the fact of the change more prominent in README or something. Just a thought 👐
