### ISSUE TITLE
Various minor issues

### ISSUE THREAD

**Issue by daephx** [glepnir/dashboard-nvim#260]
Good work on the recent update! I just moved over my config and had some things I wanted to suggest or bring to your attention.

If it's prefered, I can split these out into separate issues.

- The doom dashboard is modifiable while hyper is not,
  I assume there's a missing `set nomodifiable` for the doom theme?

- Disable fillchar EndOfBuffer: `~` for both themes.
  While it's easy to use an autocmd to disable this with `vim.opt_local.fillchar = { eob = " " }`
  Should this not be the default behaviour? I think it has a cleaner aesthetic across themes.

- Custom center description and shortcuts for doom theme has worse alignment than previous version.
  Since updating the alignment is slightly off.
  It's as if the shortcut string is not considered when calculating center position.
  
  I personally prefer the older representation for shortcuts like `SPC f r` over implicitly setting dashboard keymaps.
  As it looks more like emacs doom-dashboard and single letter keys are too easy to mess up.

Expectation:
1. The user should not be allowed to enter insert mode in doom theme dashboard buffer.
2. EndOfBuffer character `~` should not be visible in dashboard buffer.
3. Description should be properly aligned between the previous and new version of the plugin.

<details>
<summary>Minimal config: <code>init_minimal.lua</code></summary>

```lua
-- Minimal init

-- Define globals and leader keys
vim.g.mapleader = " "
vim.g.localleader = "\\"

-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- dashboard desc formatting helper
local width = 24
local pad = function(str)
  local whitespace = (" "):rep(math.abs(width - #str))
  return ("%s%s"):format(str, whitespace)
end

-- Initialize plugin list
require("lazy").setup({
  { -- Dashboard / Start screen
    "glepnir/dashboard-nvim",
    event = "VimEnter",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    opts = {
      theme = "doom",
      hide = {
        statusline = false,
        tabline = false,
        winbar = true,
      },
      config = {
        header = {
          "",
          "",
          " ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗ ",
          " ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║ ",
          " ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║ ",
          " ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║ ",
          " ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║ ",
          " ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝ ",
          "",
          string.format(
            "--- [   %s.%s.%s%s   ] ---",
            vim.version().major,
            vim.version().minor,
            vim.version().patch,
            vim.version().prerelease == true and "-dev" or ""
          ),
          "",
        },
        center = {
          {
            icon = " ",
            desc = pad("Recent"),
            key = "SPC f r",
            action = "Telescope oldfiles",
          },
          {
            icon = " ",
            desc = pad("Files"),
            key = "SPC f f",
            action = "Telescope find_files",
          },
          {
            icon = " ",
            desc = pad("Projects"),
            key = "SPC f m",
            action = "Telescope projects",
          },
          {
            icon = " ",
            desc = pad("Sessions"),
            key = "SPC s l",
            action = "Telescope session-lens search_session",
          },
          {
            icon = " ",
            desc = pad("Update"),
            key = "SPC p u",
            action = "Lazy update",
          },
          {
            icon = " ",
            desc = pad("Settings"),
            key = "SPC f v",
            action = 'lua require("plugins.telescope").search_vimfiles()',
          },
          {
            icon = " ",
            desc = pad("Exit"),
            key = "SPC   q",
            action = "exit",
          },
        },
        footer = (function()
          local plugin_path = vim.fn.stdpath("data") .. "/lazy/"
          local plugin_files = vim.fn.globpath(plugin_path, "*", 0, 1)
          local plugin_count = vim.fn.len(plugin_files)
          return { "", "", string.format("Started with %s detected plugins!", plugin_count) }
        end)(),
      },
    },
  },
})
```

</details>

<details>
<summary>
Screenshots: Shortcut alignment and modifiable buffer issues.
</summary>
</br>

`Updated Version:`

![WindowsTerminal_rgCR6k5Syz](https://user-images.githubusercontent.com/36192863/215042872-1d17c969-a4dd-43b2-9c09-225b695bfafd.gif)

`Previous Version:`

![chrome_fKxNPNAAK9](https://user-images.githubusercontent.com/36192863/215042408-92b5b9bb-18f6-4c1c-aece-137d3e86d498.png)

</details>

<details>
<summary>
Screenshots: Attempting to reduce description padding doesn't offer better results.
</summary>
</br>

Lines changed in `init_minimal.lua`
```diff
 -- dashboard desc formatting helper
- local width = 24
+ local width = 12
local pad = function(str)
  local whitespace = (" "):rep(math.abs(width - #str))
  return ("%s%s"):format(str, whitespace)
end
```

![YFRjZjBdEy](https://user-images.githubusercontent.com/36192863/215044042-db151328-841f-4c50-869a-b8c2c3afef38.png)

</details>

**Comment by glepnir** [comment]
maybe can also add keymap before the shorcut like. `SPC f f [f]` like this ? you can still use f trigger action also show keymap

**Comment by daephx** [comment]
Fixed the first issue pretty quick, thanks!

> Disable fillchar EndOfBuffer

I like the EndOfBuffer character in file buffers but disable it in dashboard, terminals, etc.
I was using `opt_local.fillchar` because my colorscheme's have `hi Normal guibg=none`.

So unfortunately, your example basically clears the higroup.
Using `guifg=black` kind of works... but there still visible.

Is there a reason using highlight is preferable? To me it just seems fillchars is cleaner; has less bugs.

Adding to `minimal_init.lua` sort of exemplify the issue.

```lua
vim.opt.termguicolors = true
vim.cmd("colorscheme default")
vim.api.nvim_set_hl(0, "Normal", { guibg = "none" })

local group = vim.api.nvim_create_augroup("DashboardOverrides", {})
vim.api.nvim_create_autocmd("FileType", {
  desc = "Apply local settings to Dashboard buffer",
  group = group,
  pattern = "dashboard",
  callback = function(opts)
    -- NOTE: Uncomment to disable EndOfBuffer:~
    -- vim.opt_local.fillchars = { eob = " " }
    -- NOTE: Can't use Normal:bg=none for EndOfBuffer:fg, it just clears higroup
    vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = "none", fg = "none" })
    -- Apply keymap settings for dashboard
    local opts = { buffer = opts.buf, remap = false, silent = true }
    -- Disable page scrolling in dashboard
    vim.keymap.set("n", "<PageDown>", "<Nop>", opts)
    vim.keymap.set("n", "<PageUp>", "<Nop>", opts)
  end,
})
```

If you're don't want to remove it, it's not a problem.
I was curious as to why it wouldn't be removed by default.

> shortcut now is a virtual text

Ok! That makes a lot of sense why the alignment was being weird.
That does make the issue a bit more annoying then, I liked how it looked previously and no amount of tweaking will get the same alignment back.

> maybe can also add keymap before

That is an option, but it's sort of deviated from doom-dashboard look too much in my opinion.

**Comment by glepnir** [comment]
you can use filetype event do it

```vim
autocmd FileType dashboard setlocal fillchars=your config

```

**Comment by glepnir** [comment]
> The style would sort of deviated from doom-dashboard look too much in my opinion. 

style not important the most thing is make it useful . if you are in dashboard buffer you can use a single character to do it why you are use space f f to do it ?  for some people still want see keymap in buffer I will add it later.

**Comment by daephx** [comment]
> you can use filetype event do it

Right, I just use the lua api for FileType events.
But alright, I'll continue to use that.

> style not important the most thing is make it useful

That's fair, though I don't think it's any less useful.
It's more preference, my keymaps work inside & outside of dashboard buffer, so it fits muscle memory.
Single character keymaps are easier but more error prone, like accidently hitting.

> for some people still want see keymap in buffer I will add it later

I'm not sure what you mean, the only issue I really have is the alignment between the description and virtualtext. It's not center as a whole unit. The virtualtext almost needs to be right-side justified to be properly displayed. It's not really a problem with single character shortcuts but is noticeable with longer shortcuts.

| Small | Medium | Large |
| --- | --- | --- |
| ![WwRA73CFcD](https://user-images.githubusercontent.com/36192863/215071198-495a7960-cd19-4774-acce-edda23f8ff29.png) | ![JwWYTOiUAj](https://user-images.githubusercontent.com/36192863/215071228-a2ec7e6a-e642-4554-a102-7899a73cdf20.png) | ![5LKNlO0xaB](https://user-images.githubusercontent.com/36192863/215071274-894f0935-fa95-45a2-bfb2-0e07afd980e3.png) |

Ideally, it would look more like:
![JwWYTOiUAj_fixed](https://user-images.githubusercontent.com/36192863/215072157-a5545f83-3931-4c25-9c0e-e6b7c8c97824.png)

**Comment by glepnir** [comment]
add space in you desc like `Exit                                                            `

**Comment by daephx** [comment]
I'm already adding space via `string.format('%s%s', desc, string.rep(" ", 24))`.
It just doesn't align with the header and footer properly.

**Comment by glepnir** [comment]
nope it not align the header and footer . just calc the center pos  according the desc text length and fill space

**Comment by glepnir** [comment]
before also not align the header and footer.

**Comment by daephx** [comment]
I ment visually, it doesn't have to factor the header/footer position.

> just calc the center pos according the desc text length and fill space

And the virtual text length is not factored into this?

**Comment by glepnir** [comment]
> And the virtual text length is not factored into this?

yes . i will add some change in there.

**Comment by daephx** [comment]
Alright, hopefully that proves to fix my issue. 
I just couldn't figure out any configuration that would give favorable results.
I hope it wasn't too much trouble getting my points across, thanks for your time.

**Comment by glepnir** [comment]
how do you feel like this 

![image](https://user-images.githubusercontent.com/41671631/215094707-6f25963d-f109-438f-a893-dc3b0b7ae3a4.png)

**Comment by rebelot** [comment]
alignment space is vim.o.columns / 3. I think it's ugly and It should default to the length of the longest desc.

**Comment by glepnir** [comment]
it calc the max_len of desc then  fill the  1/3 spaces.  add spaces in desc manually  a little trouble for some users .

**Comment by rebelot** [comment]
You realise it is ugly?

<img width="1625" alt="Screenshot 2023-01-27 at 15 01 50" src="https://user-images.githubusercontent.com/36300441/215105129-c54402d1-baca-4a74-86fd-891440836c21.png">

**Comment by glepnir** [comment]
left should move more ..some other works need to do rethink it later.

**Comment by glepnir** [comment]
revert
