### ISSUE TITLE
hyper theme print first_line

### ISSUE THREAD

**Issue by GloriousMusketeer** [glepnir/dashboard-nvim#264]
**Describe the bug**
theme hyper show print(first_line)
location: dashboard-nvim/lua/dashboard/theme/hyper.lua
line: 209

**To Reproduce**
1. Go to 'start nvim'

pd: I really don't know if it's a bug.

**Comment by glepnir** [comment]
sorry a mistake

**Comment by GloriousMusketeer** [comment]
good work, thank for dashboard :)
