### ISSUE TITLE
key_hi highlight group is not applied

### ISSUE THREAD

**Issue by matthewsia98** [glepnir/dashboard-nvim#265]
![image](https://user-images.githubusercontent.com/71731492/215267181-e25187dc-5707-40d8-96a6-8ef01f10ecc2.png)

**Comment by glepnir** [comment]
fixed and it's `hl` not `hi` both in `icon key desc`

**Comment by matthewsia98** [comment]
Probably want to change this section then. It uses `hi` here.

![image](https://user-images.githubusercontent.com/71731492/215269391-47e5a916-977d-46fb-bd97-51266b79423b.png)

**Comment by glepnir** [comment]
thanks for point it out. fixed.
