### ISSUE TITLE
Changes after update

### ISSUE THREAD

**Issue by anurag3301** [glepnir/dashboard-nvim#266]
Hey I just updated my plugin yesterday and there is a lot of changes in `dashbaord` I ported the configuration in the new style but I have some problem. The updated config is in the below-mentioned gist.
https://gist.github.com/anurag3301/c9c7d9f0f69502d3d34fdf46d9f3813c

1. Starting with first the command section doesn't seem to center correctly
![image](https://user-images.githubusercontent.com/52702259/215273710-7b9cffdc-a270-4885-a9a4-a21710836db3.png)

2. What do `icon_hi` and `hl` thing mean
3. And there was an option called `header_pad` option which I used to center the dashboard vertically, how can I use this option or there is another way to get vertically center?

**Comment by iamb4uc** [comment]
Yeah me too, I got this issue just after updating my plugins, at first my dashboard did not appear but after I did some patching from the new "config" template, it all looks messed up

**Comment by glepnir** [comment]
center align fixed.

only `hl` not `hi` a typo before

3. you can add some `''` in header . someone header too height someone too small . auto vertically  will cauesd some people confused .  or do it like 

```lua
local function pad(config)
     local height = api.nvim_win_get_height(0)
     local center = math.ceil( height / 2)
     local dbc = match.ceil((#config.center + #config.header + #config.foote) / 2)
      for i =1  center -dbc do
           table.insert(confg.header, 1, '')
      end
end
```
this work better than use pad with a hardcode number
