### ISSUE TITLE
What is the logo's font?

### ISSUE THREAD

**Issue by Boltzmachine** [glepnir/dashboard-nvim#27]
Maybe it is not an issue, but could I know how can I created the logo like this? Is it output by figlet? If so, what's the figlet's font?

**Comment by glepnir** [comment]
I forgot that URL, maybe you can search for asciitext generate in google

**Comment by baizeyv** [comment]
http://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=neovim
