### ISSUE TITLE
Pad elements

### ISSUE THREAD

**Issue by AlexvZyl** [glepnir/dashboard-nvim#272]
**Is your feature request related to a problem? Please describe.**
By default, the elements are not padded.

**Describe the solution you'd like**
Add option to pad elements.

**Describe alternatives you've considered**
Previously (before the rework) padding could be added with `footer_pad`, `header_pad` and `center_pad`.

**Additional context**

*Previously:*
![image](https://user-images.githubusercontent.com/81622310/215327252-727436e9-3d42-4f8e-a97d-6f0d677700aa.png)

*Now:*
![image](https://user-images.githubusercontent.com/81622310/215327228-0a059bc0-1d68-4709-8af5-60bbea8a275f.png)

P.S. I realize I am using different themes in the screenshots.

**Comment by glepnir** [comment]
does this code will look it better ?

```lua
local function pad(config)
     local height = api.nvim_win_get_height(0)
     local center = math.ceil( height / 2)
     local dbc = match.ceil((#config.center + #config.center - 1 + #config.header + #config.footer) / 2)
      for i =1 , center -dbc do
           table.insert(confg.header, 1, '')
      end
end
```

**Comment by AlexvZyl** [comment]
It does, but allowing the user to set the padding themselves (as it was previously) makes it very flexible and customizable.

**Comment by glepnir** [comment]
> but allowing the user to set the padding themselves (as it was previously) makes it very flexible and customizable.

not correct. think about this situation you have two computer one is macbookpro 14 one is 27 screen computer. you need change the pad by manually.  

I can add some calculate to make them center. but a little troublesome :)

**Comment by AlexvZyl** [comment]
Previously, I just used this to get the height of the terminal instance and calculate the padding based on it:

```lua
local win_height = vim.fn.winheight('%')
```

Worked on my laptop monitor and my larger monitors.

**Comment by AlexvZyl** [comment]
But yes, it should not be a hardcoded value.

**Comment by glepnir** [comment]
yes . hardcoded the pad value not smart. so dashboard can handle this.   but i just add some `''` before the header . this is enought. other pad i think you can do it in your local and it does not matter . like header top padd. you can just add some `''`
at the header table tail .  center footer pad just add some `''` at the head of footer right ? 

so add this `pad` into dashboard and do some adjust , it's enough make the content vertical  center

**Comment by AlexvZyl** [comment]
Was able to achieve this be padding `''` to the front and end of the different sections:

![image](https://user-images.githubusercontent.com/81622310/215357458-c8923bcd-ff03-425b-9a14-988c22337cd0.png)

**Comment by glepnir** [comment]
different section just have one pad .

**Comment by glepnir** [comment]
does this can make it feel good in your screen ?

```lua 
diff --git a/lua/dashboard/theme/hyper.lua b/lua/dashboard/theme/hyper.lua
index 3f6df07..438dd50 100644
--- a/lua/dashboard/theme/hyper.lua
+++ b/lua/dashboard/theme/hyper.lua
@@ -348,10 +348,15 @@ local function theme_instance(config)
     gen_center(plist, config)
     gen_footer(config)
     map_key(config, '<CR>')
-    vim.bo[config.bufnr].modifiable = false
     require('dashboard.events').register_lsp_root(config.path)
+    local size = math.floor(vim.o.lines / 2)
+      - math.ceil(api.nvim_buf_line_count(config.bufnr) / 2)
+      - 2
+    local fill = utils.generate_empty_table(size)
+    api.nvim_buf_set_lines(config.bufnr, 0, 0, false, fill)
+    vim.bo[config.bufnr].modifiable = false
+    project_delete()
   end)
-  project_delete()
 end

```

**Comment by AlexvZyl** [comment]
Places the dashboard in the center overall, which is *definitely* better than what it was and I think most people will be happy if they add just a bit of padding.

![image](https://user-images.githubusercontent.com/81622310/215423360-e75775dc-88d2-4e1e-90e7-36ae91f3a8be.png)

The only thing that would be nice (for me at least) is if it was possible to add padding between the header and the shortcuts.  I think it would be able to look very nice then.

**Comment by glepnir** [comment]
because  i think the section pad can be do it at local like you can add some `''`  in config .  add pad between the section . need write some trouble code . a littile tired on dashboard. and it works fine on my screen .so when i complete my async statusline I will relook at this. PR welcome

![image](https://user-images.githubusercontent.com/41671631/215424692-0c55b085-de06-45c9-8a8d-2053157b3ac9.png)

**Comment by AlexvZyl** [comment]
Leave it if you are tired, I am nit picking.  Will see if I can make a PR.
