### ISSUE TITLE
Trouble migrating to the reworked version

### ISSUE THREAD

**Issue by adrian-soomro** [glepnir/dashboard-nvim#273]
Hi, this is not really a feature request, but rather an ask for help - 

I've updated your plugin today and I'm struggling to get the dashboard working again. 

After updating the config options to match the new format, I was still facing the same issue, so I used the example config, still the same.

I've now left it with defaults 

![image](https://user-images.githubusercontent.com/37105695/215344158-8c72ba7a-b448-47ee-8804-68bfffa3e9c5.png)

and I'm getting the same issue. 

![image](https://user-images.githubusercontent.com/37105695/215344115-e6bce8d1-a7a4-40ef-a5be-b9dd65a94769.png)

here's my nvim version and I'm using packer
![image](https://user-images.githubusercontent.com/37105695/215344224-4c1ac239-1eb2-4f72-8678-607ddfb1fdfc.png)

Any help / advice would be much appreciated.

**Comment by glepnir** [comment]
update your neovim verison
