### ISSUE TITLE
The dashboard is not displayed.

### ISSUE THREAD

**Issue by yangxianglong** [glepnir/dashboard-nvim#277]
After executing PackerSync to update the plugin.
The dashboard is not displayed.
<img width="905" alt="image" src="https://user-images.githubusercontent.com/55280276/215716537-87b0d4c4-b717-48dc-b946-07024ba0881e.png">

**Comment by glepnir** [comment]
please see doc.

**Comment by yangxianglong** [comment]
It was displaying fine before the update.
what should i change?

**Comment by glepnir** [comment]
you need reconfig it . new version is breakchange. doc has an example config.

**Comment by yangxianglong** [comment]
I got it, thank you.
