### ISSUE TITLE
The following problem occurred when I used PackerSync

### ISSUE THREAD

**Issue by yellowfishee** [glepnir/dashboard-nvim#279]
I'm going to add a comment plugin, so I used PackerSync, and the following problem occurred. Also, I use command `nvim .`  tree-nvim won't display properly
nvim version: NVIM v0.9.0-dev

----- 
Error detected while processing UIEnter Autocommands for "*":
Error executing lua callback: vim/_meta.lua:0: no such option: 'stc'
stack traceback:
        [C]: in function 'nvim_get_option_info'
        vim/_meta.lua: in function '__index'
        vim/_meta.lua: in function ''
        vim/_meta.lua: in function '__newindex'
        .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:82: in function 'buf_local'
        .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:236: in function 'instance'
        ...te/pack/packer/start/dashboard-nvim/plugin/dashboard.lua:12: in function <...te/pack/packer/start/dashboard-nvim/plugin/dashboard.lu
a:10>

**Comment by glepnir** [comment]
update your neovim

**Comment by yellowfishee** [comment]
neovim is already the newest version (0.9.0~ubuntu1+git202302011604-4cc0d6b85-333b5866f-c30891480~ubuntu22.04.1).
The problem still exists. It's not solved yet.  and dashboard doesn't show any errors anymore，but it's blank.
![image](https://user-images.githubusercontent.com/81470010/216312150-a39c1ba4-862e-4a1b-b54c-138a3db466cf.png)

**Comment by glepnir** [comment]
stc is new option in neovim you need update your neovim first. second please read doc ? there already update to new version few days ago. please search first not create issue.

**Comment by yellowfishee** [comment]
sorry, I updated nvimtree config, Now it's back on track.
thanks
