### ISSUE TITLE
A error reported when using preview

### ISSUE THREAD

**Issue by JiDonghao0121** [glepnir/dashboard-nvim#280]
the following error will be reported when opening the recent files if preview is used to generate the header.
![image](https://user-images.githubusercontent.com/52343820/216625357-ac441ea9-c486-4d2d-a029-9613c5631b0d.png)

**Comment by glepnir** [comment]
reproduce step fillissue template

**Comment by JiDonghao0121** [comment]
Actually the error happens when opening any files directly in the dashboard, such as using mru hotkeys or commands like `:enew`, `:e filepath`. But, Opening files using recent projects and nvimtree won't cause this error.
