### ISSUE TITLE
Get error when dashboard start up 

### ISSUE THREAD

**Issue by YangEfei** [glepnir/dashboard-nvim#284]
**Describe the bug**
When I enter nvim with the latest dashboard(97aaa20), I got the error below:
```text
Error executing vim.schedule lua callback: ...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:319: (binary): cannot load malformed bytecode
stack traceback:
	[C]: in function 'assert'
	...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:319: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
And I found that it's a command that load the project lists.
So I think I can try to delete the project lists by `DbProjectDelete count` command.
However, because it has been cored dump at this line, I can not run this command.
Then, I tried to ignore this command by commentting thess code:
```lua
utils.async_read(
    config.path,
    vim.schedule_wrap(function(data)
      -- local dump = assert(loadstring(data))
      -- local list = dump()
      -- if list then
      --   list = vim.list_slice(list, #list - config.project.limit)
      -- end
      -- for _, dir in ipairs(list or {}) do
      --   dir = dir:gsub(vim.env.HOME, '~')
      --   table.insert(res, (' '):rep(3) .. ' ' .. dir)
      -- end

      if #res == 0 then
        table.insert(res, (' '):rep(3) .. ' empty project')
      else
        reverse(res)
      end
      table.insert(res, 1, config.project.icon .. config.project.label)
      table.insert(res, 1, '')
      table.insert(res, '')
      callback(res)
    end)
  )
```
I can get into dashboard by this method. 
However, when I tried to run t he command `DbProjectDelete count` to fix up this error, I got the same errors again. Due to it will read project_list in the `project_delete()` too.

I don't know why my project_list will have malformed bytecode. And I tried to search it by Google. However, I can not get any useful information about it...

BTW, I tried to print data too, and got these
```text
^[LJ^B^H<ac>^Areturn { "/home/yangyifei.yyf/workspace/cpp_m2/src", "/data/work/yangyifei.yyf/issue-...refacotring-/home/yangyifei.yyf/workspace/cpp_m2/src,/data/work/yangyifei.yyf/issue-47514483^A^A^@^@
```
Maybe the `^A^A^@^@` is the 'malformed bytecode' I guess?

**To Reproduce**
Has mentioned above.

**Expected behavior**
Get into dashboard without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/54932475/216823621-5ea4cd83-e23f-45e1-8b8b-fce6bb8aed9c.png)

**Comment by glepnir** [comment]
currently remove the cache file. i had add a auto remove when list count > 15.  this should better than remove by manually.

**Comment by glepnir** [comment]
this new behavior can avoid this error i guess...

**Comment by YangEfei** [comment]
emmm... so u meant that it caused by there're too many projects in the project list?
idk what happened here.
I tried to remove the cache file in `$HOME/.cache/nvim/dashboard` directly. The project list is really mpty now, and dashboard works correctly too.
But there're no projects in the project list even though I opened some projects to verify it...
Maybe there're some other fails here. I will try to find out it.

**Comment by glepnir** [comment]
remove cache file then there is no project because it save in this file. don't know how to trigger this error. but i had a auto clean ..so i think should be useful.. just try a while .

**Comment by YangEfei** [comment]
I'm a little busy these two days. 
Sorry for that I haven't checked why there're no projects after I removed the project cache (and I have opened some projects, there're still no projects in the list).
And I found that there's a error when the project list is empty. When I type the shortcut to visit the `empty project`, it will get some error:
```text
E5108: Error executing lua: ...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:178: bad argument #1 to 'sub' (number expected, got nil)
stack traceback:
	[C]: in function 'sub'
	...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:178: in function <...e/nvim/lazy/dashboard-nvim/lua/dashboard/theme/hyper.lua:175>
```
For example, type `p` in this dashboard and get the error.
![image](https://user-images.githubusercontent.com/54932475/216916287-c12a7e84-78aa-4a14-ae51-978ef62ed811.png)

I think if the project list is empty, we should not provide the shortcut to visit it.

**Comment by glepnir** [comment]
fixed this.

**Comment by YangEfei** [comment]
I tried reset my dashboard to 64b5db5e, project list comes back and works correctly.
Then I pull master again, it still works right.
I use `git diff 64b5db5e` to analyze where maybe cause error, but I can not find why... There're few codes changes between these two commits.

I close this issue temporarily. If I met it again or I found out why, I will reopen it.
Thanks a lot~

**Comment by YangEfei** [comment]
BTW, you can try to remove cache file and check whether the project list will work correctly.
I have tried this 3 times, and the project list can not add any project after I removed it every time.
However, I can not find why from the codes... For lua, I'm a newbie. 😓

**Comment by glepnir** [comment]
> I have tried this 3 times, and the project list can not add any project after I removed it every time.

because all the project store in this file . if you removed it. noting can be read. so it's empty. I don't store anything in memory. event the all strings in dashboard. all of theme will clean after you open a file. but it can still work when you called the dashboard command it will read the config cache. there has two caches. one for project one for config.

**Comment by glepnir** [comment]
> I have tried this 3 times, and the project list can not add any project after I removed it every time.

because all the project store in this file . if you removed it. noting can be read. so it's empty. I don't store anything in memory. event the all strings in dashboard. all of theme will clean after you open a file. but it can still work when you called the dashboard command it will read the config cache. there has two caches. one for project one for config.

**Comment by YangEfei** [comment]
But i think if it found that `cache` file is empty or not exist, it will create it and then the project which opened later should be append correctlly?
The project list will be always empty if I removed the `cache` file now.

The step to reproduce it:
1. remove the file `$HOME/.cache/nvim/dashboard/cache`
2. open a project by execute `nvim` at the root directory of the project
3. redo step 2 in different projects some times.
4. run `nvim` anywhere, and the dashboard is still empty.
5. git reset --hard 64b5db5ea1207fe30ea77553b652adb4d5f58763
6. redo step 2-3
7. redo 4, and the project list comes back

**Comment by glepnir** [comment]
file should have lsp root. 

![jump](https://user-images.githubusercontent.com/41671631/216946564-3ddb024f-82cf-4bd5-86e3-00d651e23d71.gif)

**Comment by YangEfei** [comment]
Yes I got it from the code. And u can see that I loaded lsp at the right bottom, and there're still no any projects.
![Kapture 2023-02-06 at 21 52 09](https://user-images.githubusercontent.com/54932475/216990665-6bed6c95-2a39-4c5d-9ed6-8422461aaea3.gif)

idk why it can not reproduce this question in ur place.
It doesn't matter. I think  I can find out the result by some output. (Due to I'm not skilled with lua, it needs some time 😓... I even can not output some necessary information by print right now)

**Comment by YangEfei** [comment]
https://github.com/glepnir/dashboard-nvim/pull/287
OK, I found out it by dichotomous method.
If I change the codes like these:
```diff
diff --git a/lua/dashboard/events.lua b/lua/dashboard/events.lua
index f971143..d78fc9c 100644
--- a/lua/dashboard/events.lua
+++ b/lua/dashboard/events.lua
@@ -32,9 +32,11 @@ function au.register_lsp_root(path)
             assert(not err, err)
             local before = assert(loadstring(data))
             local plist = before()
-            if #plist > 15 then
-              plist = vim.list_slice(plist, 15)
-            end
+            print(plist)
+            print(#plist)
+            -- if #plist > 15 then
+            --   plist = vim.list_slice(plist, 15)
+            -- end
             plist = vim.tbl_filter(function(k)
               return not vim.tbl_contains(projects, k)
             end, plist or {})
```
The cache file which I removed will be back, but it's still empty.

And then I try to remove the code `print(#plist)`, which I think maybe core since it's nil and can not get the length (idk whether lua will set it to 0 if the table is nil). Then the projects can be set into cache file correctly.

So I move the judgement later, to avoid this situation. It has been verified in my environment, it works well.

**Comment by YangEfei** [comment]
BTW, idk how to print it in the callback function which will be called when the vim leave.
I just try to print it , but as a matter of fact, i didn't get any output...
The above content is only based on my own judgment, if there are incorrect places welcome to point out~
Thanks a lot
