### ISSUE TITLE
I can't get Doom theme to look like the one shown in README.md

### ISSUE THREAD

**Issue by comiluv** [glepnir/dashboard-nvim#285]
**Describe the bug**
I can't get the Doom theme that's shown on the README.md as below screenshot:
<img width="310" alt="2023-02-05 001547" src="https://user-images.githubusercontent.com/41671631/214518543-d7d6afbf-f405-4a6f-a505-568c5a101e92.png">

**To Reproduce**
1. Install using lazy.nvim
```lua
	{
		"glepnir/dashboard-nvim",
		event = "VimEnter",
		dependencies = "nvim-tree/nvim-web-devicons",
	},
```
2. Copy-paste Doom theme example config from README.md in init.lua
```lua
local db=require'dashboard'
db.setup({
  theme = 'doom',
  config = {
    header = {}, --your header
    center = {
      {
        icon = ' ',
        icon_hl = 'Title',
        desc = 'Find File           ',
        desc_hl = 'String',
        key = 'b',
        keymap = 'SPC f f',
        key_hl = 'Number',
        action = 'lua print(2)'
      },
      {
        icon = ' ',
        desc = 'Find Dotfiles',
        key = 'f',
        keymap = 'SPC f d',
        action = 'lua print(3)'
      },
    },
    footer = {}  --your footer
  }
})
```
3. See error

**Expected behavior**
<img width="310" alt="2023-02-05 001547" src="https://user-images.githubusercontent.com/41671631/214518543-d7d6afbf-f405-4a6f-a505-568c5a101e92.png">

**What actually happens**
<img width="836" alt="2023-02-06 070115" src="https://user-images.githubusercontent.com/19642705/216848469-971a26f5-6df4-4b93-bf17-965d0efbb8ea.png">

** Notes **
I also tried removing header table from config table but result looks like below:
<img width="836" alt="2023-02-06 070617" src="https://user-images.githubusercontent.com/19642705/216848817-f1cae329-feb8-483f-bb6a-055ff7452f0b.png">

**Comment by comiluv** [comment]
Copying the first header from https://github.com/glepnir/dashboard-nvim/wiki/Ascii-Header-Text resulted in below screenshot
<img width="836" alt="2023-02-06 072819" src="https://user-images.githubusercontent.com/19642705/216849572-f52a0b68-b74b-41ca-8bb6-3c705299437b.png">

**Comment by glepnir** [comment]
change a terminal and rainbow you need install lolcat
