### ISSUE TITLE
feat(doom): allow header and footer to be functions

### ISSUE THREAD

**Issue by rebelot** [glepnir/dashboard-nvim#289]
allow `config.{header,footer}` to be functions.

this allows:

```lua
require("dashboard").setup({
    theme = "doom",
    config = {
        header = {...},
        center = {...},
        footer = function()
            return string.format("Startup time: %s ms", require'lazy'.stats().startuptime)
        end,
    },
})
``` 

This does not work if we cannot defer the call to `lazy.stats` as setup isn't finished by the time dashboard config is sourced

**Comment by glepnir** [comment]
startuptime can be in builtin i think

**Comment by rebelot** [comment]
beautiful! thanks @glepnir !!! <3
