### ISSUE TITLE
Typo in autoload/dashboard/telescope.vim

### ISSUE THREAD

**Issue by p00f** [glepnir/dashboard-nvim#29]
Lines 6 and 10 have Tele*sope* instead of Tele*scope*_

**Comment by glepnir** [comment]
fixed Thanks.

**Comment by p00f** [comment]
The function defined telescope.nvim is `TelescopeFindFile`, the function called in dashboard.nvim is `TelescopeFindFiles`

**Comment by glepnir** [comment]
Oh Sorry.. I forget I changed command in telescope.vim ..check PR.https://github.com/nvim-lua/telescope.nvim/commit/18a91f27143628d732ae339b5df3996e3066fdb6

**Comment by glepnir** [comment]
fixed.
