### ISSUE TITLE
Recent Projects - show empty project

### ISSUE THREAD

**Issue by shy-robin** [glepnir/dashboard-nvim#292]
When I open nvim,  it does not display my recent projects in dashboard.
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/59857729/217488141-7da0dc06-cb06-4cb9-aac1-7a8a6f827dbf.png">

**Comment by glepnir** [comment]
only support show lsp project

**Comment by shy-robin** [comment]
> only support show lsp project

Thanks for your reply. But what does lsp project mean? I use coc.nvim to get lsp service, when I open a typescript project, I can get typescript syntax prompt, but it still show empty project.

**Comment by glepnir** [comment]
only support built-in lsp.  don't use coc. pr welcome

**Comment by shy-robin** [comment]
> only support built-in lsp. don't use coc. pr welcome

I got it, thanks.

**Comment by zhaogangang** [comment]
i think here's bug, i meet some bug for days ago, just like  "cannot load malformed bytecode", and i clean cache data, then open correctly, but  meet avove bug, i use built-in lsp

**Comment by glepnir** [comment]
#287

**Comment by zhaogangang** [comment]
thanks
