### ISSUE TITLE
cache issue after a system crash

### ISSUE THREAD

**Issue by sadtab** [glepnir/dashboard-nvim#293]
**Describe the bug**
My system crashed during a heavy compile of linux kernel. After the crash I got 
```
 Error executing vim.schedule lua callback: ...acker/start/dashboard-nvim/lua/dashboard/theme/hyper.lua:100: (binary): cannot load malformed bytecode
stack traceback:
        [C]: in function 'assert'
        ...acker/start/dashboard-nvim/lua/dashboard/theme/hyper.lua:100: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
I removed and reinstalled the plugin but still had the same issue, the solution was to remove `.cache/nvim/dashboard` 
I'm not sure if this is reproducible but in the Neovim's chat room folke proposed to "clear the cache when it encounters invalid byte code", I'm not a lua guy otherwise I would post a PR for it.

**To Reproduce**
The cache file should be altered to "malformed badbyte" thing

**Expected behavior**
Start nvim and dashboard won't load with posted error codes

**Screenshots**
N/C

**Comment by glepnir** [comment]
#287
