### ISSUE TITLE
Change Directory when file selected and none random keys for `Hyper`

### ISSUE THREAD

**Issue by LamprosPitsillos** [glepnir/dashboard-nvim#297]
**Is your feature request related to a problem? Please describe.**
1. Random keys on the dashboard make it impossible to quickly see and go to a file for me.
2. Is there a way to make it that when selecting a MRU item it also changes to that directory ?
3. Is there a way to bind `q` to close the dashboard ?

**Describe the solution you'd like**
1. Is there a way to make it to numbers?
2. I am thinking of doing a PR if there is none
3. Maybe an auto command could fix this

**Comment by glepnir** [comment]
> Is there a way to make it to numbers?

maybe can add an option to control this letter or number.

> Is there a way to bind q to close the dashboard ?

why you wan quit it ? and what is the quit mean ? delete dahsboard buffer create a scratch  buffer it works like no dashboard plugin. 

> Is there a way to make it that when selecting a MRU item it also changes to that directory ?

very easy to do .

**Comment by Chilly-Blaze** [comment]
> > Is there a way to make it to numbers?
> 
> maybe can add an option to control this letter or number.
> 
> > Is there a way to bind q to close the dashboard ?
> 
> why you wan quit it ? and what is the quit mean ? delete dahsboard buffer create a scratch buffer it works like no dashboard plugin.
> 
> > Is there a way to make it that when selecting a MRU item it also changes to that directory ?
> 
> very easy to do .

I think he means to quit nvim,as do I.
I bind 'q' to delete buffer as well as quit the nvim instead of `:wq` or `ZZ`.

**Comment by glepnir** [comment]
```lua
vim.api.nvim_create_autocmd('FileType', {
   pattern = 'dashboard',
  callback = function(opt)
       vim.keymap.set('n','q', function()
          if vim.bo[opt.buf] == 'dashboard' then
                vim.cmd('quit')
          end
       end,{ buffer = opt.buf, remap = true})
  end

**Comment by glepnir** [comment]
[x] auto change dir
[x] map q you can do it in local

**Comment by glepnir** [comment]
`shortcut_type` .value is `letter` or `number`.

**Comment by ihsanpraditya** [comment]
I had changed it from letter to number. Nothing is changed until I did `PackerSync`.
