### ISSUE TITLE
Can't customize dashboard

### ISSUE THREAD

**Issue by lbollar** [glepnir/dashboard-nvim#299]
**Describe the bug**
Tried various configs including copying others, but nothing changes my dashboard.

**To Reproduce**
Currently using this config exactly [here](https://github.com/jdhao/nvim-config/blob/master/lua/config/dashboard-nvim.lua)

```
    use { "glepnir/dashboard-nvim", event = "VimEnter",
      config = [[require('config.dashboard-nvim')]]
    }
```

**Screenshots**
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/6322326/218161535-ff94a089-e591-4822-b5bc-f935d884a4dd.png">

**Comment by glepnir** [comment]
please read doc.

**Comment by lbollar** [comment]
I read all, the docs are pretty sparse. I gave up and moved to alpha.

**Comment by lbollar** [comment]
That wasn’t only thing I tried. I also tried just changing config settings like in Readme. Nothing would ever change.

**Comment by glepnir** [comment]
make me laugh. please don't use my plugin
