### ISSUE TITLE
remove project section in hyper theme

### ISSUE THREAD

**Issue by gennaro-tedesco** [glepnir/dashboard-nvim#300]
**Describe the bug**
A question more than a bug: is it possible to remove the project section in the `hyper` theme?

I have tried setting
```lua
require("dashboard").setup({
  theme="hyper",
  config = {
    ..
    ..
    project = {}
  }
})
```

both `project = {}` or `project{limit = 0}` but it seems to always default to at least 1. I presume it is not possible to remove it altogether?

**Comment by glepnir** [comment]
right . currently some codes of mru and porject has some coupling. So if need to support disabling, there need to decouple a part of the codes.  can add an option like `project.enable = false` to disable it . 

and i want to know why you want disable it

**Comment by gennaro-tedesco** [comment]
> and i want to know why you want disable it

Simply to save some room in the dashboard :). In my case I use session managers to browse among projects so I need not select them from the dashboard.

No urgency or special need to do so, I was just wondering if it was possible already with the current setups.

**Comment by glepnir** [comment]
support disable later. 

> It would be however super cool to allow users to even customise their own sections in terms of what each section displays

already in my mind. a little trouble

**Comment by gennaro-tedesco** [comment]
Thank you for taking the time! Feel free to close this issue if not planned or to keep it open for future reference :)

**Comment by glepnir** [comment]
disable project will support . support custom the whole buffer of dashboard will in next version.  i will close this issue in a commit which add an option to disable project
