### ISSUE TITLE
General field `disable_move` does not work `doom` theme

### ISSUE THREAD

**Issue by Hanaasagi** [glepnir/dashboard-nvim#303]
**Describe the bug**

Cursor motion is not disabled when set `disable_move = true` in `doom` theme. It only works in `hyper` theme.

**To Reproduce**
Minimal Reproducible Code

``` Lua
require('dashboard').setup({
  disable_move = true,
  config = { week_header = { enable = true } },
  theme = 'doom' 
})
```

**Expected behavior**

Could not move cursor when set `disable_move = true`.

<hr>

Maybe following code is missing in `doom.lua`.

https://github.com/glepnir/dashboard-nvim/blob/c6a0eb974caa6728dd6e9bd48dec580ab0bf9905/lua/dashboard/theme/hyper.lua#L361-L363

**Comment by glepnir** [comment]
design . I am not control it in doom.

**Comment by Hanaasagi** [comment]
Emm, OK.
