### ISSUE TITLE
Could not set just two shortcuts in `hyper`  dashboard

### ISSUE THREAD

**Issue by Hanaasagi** [glepnir/dashboard-nvim#304]
**Describe the bug**

I want to set just two shortcuts in dashboard. But pre-defined value is displayed. Please see the screenshot, a extra field `version` is displayed.

**To Reproduce**
Minimum recurrence code

```Lua
require('dashboard').setup({
  theme = 'hyper',
  config = {
    shortcut = {
      { icon = '🍡 ', icon_hl = '@variable', desc = 'Files', action = 'Telescope file_browser', key = 'F' },
      { icon = '🍥 ', icon_hl = '@variable', desc = 'Configuration', action = 'Telescope dotfiles', key = 'C' },
    },
    footer = {}
  }
})

```

**Expected behavior**

Only  `🍡 Files[F]  🍥 Configuration[C]` is displayed in screen.

**Screenshots**

![2023-02-14_22-15](https://user-images.githubusercontent.com/9482395/218764087-2b39a09e-4b09-43d9-a0cb-1bbcf3fae917.png)

<hr>

Maybe override the default value would be better, not extending them.

https://github.com/glepnir/dashboard-nvim/blob/c6a0eb974caa6728dd6e9bd48dec580ab0bf9905/lua/dashboard/theme/hyper.lua#L6-L10

I currently use a temporary solution:
```Lua
          shortcut = {
            { icon = '🍡 ', icon_hl = '@variable', desc = 'Files', action = 'Telescope file_browser', key = 'F' },
            { icon = '🍥 ', icon_hl = '@variable', desc = 'Configuration', action = 'Telescope dotfiles', key = 'C' },
            { icon = '', desc= ''},
          },

```

**Comment by glepnir** [comment]
fix it tomorrow sleep time
