### ISSUE TITLE
Example showing how to add loaded plugins

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [glepnir/dashboard-nvim#31]
This might seems sort of obscure but in the examples in the wiki the default has a footer of "neovim loaded 63 plugins". It's not in the README but skimming through the code it looks like this information is obtained by using the dein plugin manager.

Maybe have a section in the wiki for code snippets for getting the same the in the footer. For example if the user has fd installed and is using packer to install plugins.

```vim
" we ignore the directories 'start' and 'opt'
let g:total_plugins = trim(system("fd -d 2 . $HOME'/.local/share/nvim/site/pack/packer' | head -n -2 | wc -l"))
let g:dashboard_custom_footer = ['                               loaded '. g:total_plugins .' plugins     ']
```

Note `~/.local/share/nvim/site/pack/*/opt` and ` ~/.local/share/nvim/site/pack/*/start` are the default runtime for plugins in neovim. Any plugin manager that installs to this directory can use this could if they change packer to whatever their package manager uses.

**Comment by glepnir** [comment]
Yep. dashboardh can get total plugins from vim-plug or dein. the packer use native package path and it doesn't provide any api for get plugins number.   your code snippet seems ok, but if custom the packer root path the code snippet will be failed.
Another question why not use `globpath` function to get the total folder number that under  `pack/*/opt` and `pack/*/start` 
I think it's better  than use  command `fd`?

**Comment by Th3Whit3Wolf** [comment]
What would globpath command look like?

**Comment by glepnir** [comment]
```vim
let path = os.getenv('HOME').'/.local/share/nvim/site/pack/packer'
echo len(filter(split(globpath(path, '.*'), '\n'), '!isdirectory(v:val)')) -- will got the folder count number.
```

**Comment by Th3Whit3Wolf** [comment]
That is much better

**Comment by Th3Whit3Wolf** [comment]
Now that I think about it though that tells you how many total plugins you have, not which ones you have loaded.

**Comment by Th3Whit3Wolf** [comment]
```lua
function totalPlugins()
    paths = {};
    for match in (package.path..';'):gmatch("(.-)"..';') do
        table.insert(paths, match);
    end
    for k,_ in pairs(paths) do
        if string.match(paths[k], "nvim/site/pack/") then
        count = count + 1
        end
    end
    print('plugins loaded: ' .. count)
end
```

If you using neovim you could use something like this

**Comment by glepnir** [comment]
All your code examples only work under *nix, so you need to consider the windows environment.hmm why not
`vim.fn.globpath()`,Excessive use of regularization is not efficient.

**Comment by Th3Whit3Wolf** [comment]
Do you know what the default runtime is on Windows? I just assumed it was something similar with a different prefix. `vim.fn.globpath()` is great.

**Comment by p00f** [comment]
> Now that I think about it though that tells you how many total plugins you have, not which ones you have loaded.

The number of folders in `~/.local/share/nvim/site/pack/packer/start` are loaded on start, so that would be the correct number of plugins...

**Comment by Th3Whit3Wolf** [comment]
> The number of folders in `~/.local/share/nvim/site/pack/packer/start` are loaded on start, so that would be the correct number of plugins (am I missing a special case?)

Commonly optional plugins are loaded on filetype, if you use `rust.vim` you probably only need it when working on rust files. Some plugins are loaded on command or keymap as well. You may be working on these in other buffers and they would be loaded.

**Comment by p00f** [comment]
You're only supposed to see the number of plugins loaded on startup, not the other ones

**Comment by Th3Whit3Wolf** [comment]
by using `:Dashboard`

**Comment by p00f** [comment]
oh

**Comment by glepnir** [comment]
closed. plan to rewrite it by lua.
