### ISSUE TITLE
Error while config in packer

### ISSUE THREAD

**Issue by Strong214356** [glepnir/dashboard-nvim#310]
while starting, packer is giving me this error : 
Erreur détectée en traitant /home/tidian/.config/nvim/init.lua :
E5113: Error while calling lua chunk: ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:1023: /home/tidian/.config/nvim/lua/palsfreniers/packer.lua:89: module 'da
shboard' not found:
        no field package.preload['dashboard']
        no file './dashboard.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/dashboard.lua'
        no file '/usr/local/share/lua/5.1/dashboard.lua'
        no file '/usr/local/share/lua/5.1/dashboard/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/dashboard.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/dashboard/init.lua'
        no file './dashboard.so'
        no file '/usr/local/lib/lua/5.1/dashboard.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/dashboard.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        ...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:1023: in function <...e/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:989>
        [C]: in function 'require'
        /home/tidian/.config/nvim/lua/palsfreniers/init.lua:3: in main chunk
        [C]: in function 'require'
        /home/tidian/.config/nvim/init.lua:1: in main chunk

this is my config in packer : 
```lua
use {
		'glepnir/dashboard-nvim',
		event = 'VimEnter',
		config = require('dashboard').setup {
			theme = 'doom',
			header = {
				' ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗',
				' ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║',
				' ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║',
				' ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║',
				' ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║',
				' ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝',
			},
			center = {
				icon = '',
				icon_hl = 'group',
				desc = 'description',
				desc_hl = 'group',
				key = 'shortcut key in dashboard buffer not keymap !!',
				key_hl = 'group',
				action = '',
			},
			footer = {},
		},
		requires = {'nvim-tree/nvim-web-devicons'}
	}

```

**Comment by glepnir** [comment]
config is a function type
