### ISSUE TITLE
Can i customize project font color like your README example ?

### ISSUE THREAD

**Issue by Coien-rr** [glepnir/dashboard-nvim#313]
**Describe the bug**
Can i customize project font color like your README example 

**To Reproduce**
ColorScheme use zephyr-nvim
Dashboard use Example config of hyper

**Screenshots**
<img width="893" alt="image" src="https://user-images.githubusercontent.com/83146518/221105875-fc2f9a8f-3b6c-45a6-bbff-a065cf4bdff0.png">

but font color seem not works

**Comment by glepnir** [comment]
in doc

```
DashboardProjectTitle DashboardProjectTitleIcon DashboardProjectIcon
DashboardMruTitle DashboardMruIcon DashboardFiles DashboardShotCutIcon
```

**Comment by Coien-rr** [comment]
Oops! I thought there are built-in highlight groups，It is now successfully set! thank your reply
