### ISSUE TITLE
Unable to set custom header

### ISSUE THREAD

**Issue by default-303** [glepnir/dashboard-nvim#318]
**Describe the bug**
I'm try to set a custom header but it does not reflect when I restart nvim. I'm using `hyper` and tried setting the ascii art in my config. It does not seem to work.

**Config**

in after/plugin/dashboard.lua
```
local status, dashboard = pcall(require, "dashboard")

if not status then
    return
end

local custom_banner ={
    "", 
    "", 
    " ⣿⣿⣷⡁⢆⠈⠕⢕⢂⢕⢂⢕⢂⢔⢂⢕⢄⠂⣂⠂⠆⢂⢕⢂⢕⢂⢕⢂⢕⢂ ",
    " ⣿⣿⣿⡷⠊⡢⡹⣦⡑⢂⢕⢂⢕⢂⢕⢂⠕⠔⠌⠝⠛⠶⠶⢶⣦⣄⢂⢕⢂⢕ ",
    " ⣿⣿⠏⣠⣾⣦⡐⢌⢿⣷⣦⣅⡑⠕⠡⠐⢿⠿⣛⠟⠛⠛⠛⠛⠡⢷⡈⢂⢕⢂ ",
    " ⠟⣡⣾⣿⣿⣿⣿⣦⣑⠝⢿⣿⣿⣿⣿⣿⡵⢁⣤⣶⣶⣿⢿⢿⢿⡟⢻⣤⢑⢂ ",
    " ⣾⣿⣿⡿⢟⣛⣻⣿⣿⣿⣦⣬⣙⣻⣿⣿⣷⣿⣿⢟⢝⢕⢕⢕⢕⢽⣿⣿⣷⣔ ",
    " ⣿⣿⠵⠚⠉⢀⣀⣀⣈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣗⢕⢕⢕⢕⢕⢕⣽⣿⣿⣿⣿ ",
    " ⢷⣂⣠⣴⣾⡿⡿⡻⡻⣿⣿⣴⣿⣿⣿⣿⣿⣿⣷⣵⣵⣵⣷⣿⣿⣿⣿⣿⣿⡿ ",
    " ⢌⠻⣿⡿⡫⡪⡪⡪⡪⣺⣿⣿⣿⣿⣿⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃ ",
    " ⠣⡁⠹⡪⡪⡪⡪⣪⣾⣿⣿⣿⣿⠋⠐⢉⢍⢄⢌⠻⣿⣿⣿⣿⣿⣿⣿⣿⠏⠈ ",
    " ⡣⡘⢄⠙⣾⣾⣾⣿⣿⣿⣿⣿⣿⡀⢐⢕⢕⢕⢕⢕⡘⣿⣿⣿⣿⣿⣿⠏⠠⠈ ",
    " ⠌⢊⢂⢣⠹⣿⣿⣿⣿⣿⣿⣿⣿⣧⢐⢕⢕⢕⢕⢕⢅⣿⣿⣿⣿⡿⢋⢜⠠⠈ ",
    " ⠄⠁⠕⢝⡢⠈⠻⣿⣿⣿⣿⣿⣿⣿⣷⣕⣑⣑⣑⣵⣿⣿⣿⡿⢋⢔⢕⣿⠠⠈ ",
    " ⠨⡂⡀⢑⢕⡅⠂⠄⠉⠛⠻⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢋⢔⢕⢕⣿⣿⠠⠈ ",
    " ⠄⠪⣂⠁⢕⠆⠄⠂⠄⠁⡀⠂⡀⠄⢈⠉⢍⢛⢛⢛⢋⢔⢕⢕⢕⣽⣿⣿⠠⠈ ",
    "", 
    "", 
    }

dashboard.setup{
    config = {
        theme = "hyper", 
        header = custom_banner
    }
}

```

in lua/default/packer.lua: 

```
    use {
        'glepnir/dashboard-nvim',
        event = 'VimEnter',
        requires = { 'nvim-tree/nvim-web-devicons' }
    }

```
**Expected behavior**
The plugin displays the custom header as set in its config.

**Comment by glepnir** [comment]
packercompile

**Comment by dinko-pehar** [comment]
@default-303 I set it up by placing header inside `config` as:

```vimrc
require('dashboard').setup({
                theme = 'hyper',
                config = {
                    header = banner,
                }
            })

```

**Comment by lbollar** [comment]
You keep telling everyone to compile but don’t put in docs.

**Comment by glepnir** [comment]
why i need put it in doc ? it is packer usage ? why you don't read packer doc? i think it told me to sync or compile ?

**Comment by lbollar** [comment]
Users are expecting their config to be picked up like most configs. I don’t remember last time I had to sync or compile for config change besides trying dashboard. That’s why people keep saying these things. They expect it.

**Comment by lbollar** [comment]
I’m guessing it’s the way dashboard is setup to be more efficient. But I don’t think that is obvious to casual user.

**Comment by glepnir** [comment]
you know how packe works ? it generate a compile file and load it. it include all your plugins loaded rule and config. if you changed any plugins config you must to sync or compile. not issue of dashboard. if you don't like this way change to lazy.nvim it no need you to compile or sync.
