### ISSUE TITLE
CWD goes back 1 directory when opening a file from Most Recent files

### ISSUE THREAD

**Issue by TroySigX** [glepnir/dashboard-nvim#319]
**Describe the bug**
I have the following code structure:
```
   src/
     - child 1
         + file 1
         + file 2
     - child 2
     - child 3
```
     
I enter "child 1" directory, enter nvim and access file 1 from MRU in dashboard. When I check the CWD (using :lua print(vim.fn.getcwd()), it points to the src directory

**To Reproduce**
1. Go to a subdirectory
2. Access a file in that subdirectory from MRU list on dashboard

**Expected behavior**
When printing out CWD, it should point to "child 1" directory.

**Screenshots**
![image](https://user-images.githubusercontent.com/88051085/221884998-540c9571-e552-472f-8379-e0ac05ec3462.png)
![image](https://user-images.githubusercontent.com/88051085/221885526-ce12c6fd-9bc3-4797-a3d0-f52b22e2efbb.png)

**Comment by TroySigX** [comment]
I believe that it has something to do with typescript, as the bug doesn't occur with my other directories.

**Comment by glepnir** [comment]
because it find the root is src folder.

**Comment by TroySigX** [comment]
No, if you look at the screenshots, you'll notice that I'm in folder /mnt/HDD/umass/umass-projects/cs220/03-more-image-processing-with-hof (1st screenshot), but when I enter the file (2nd screenshot) and print out the cwd again, it shows /mnt/HDD/umass/umass-projects, meaning 2 folders back

**Comment by glepnir** [comment]
you in ` /mnt/HDD/umass/umass-projects/cs220/03-more-image-processing-with-hof` this folder open a file then the `pwd` is `/mnt/HDD/umass/umass-projects` . this folder has vcs right ? so the hyper found it and set it to root.

**Comment by attila-ks** [comment]
In my case, CWD changes to /home/<username> after I open a recent project from Dashboard and select a file with the automatically opened Telescope plugin. I don't know if this is normal behavior or not

**Comment by glepnir** [comment]
nope dahshboard only change the dir to root if find `.git .svn` when `change_to_vcs_root` option is true now. if not found dashboard won't change your pwd .
