### ISSUE TITLE
Dashboard incorrectly shows number of loaded packages

### ISSUE THREAD

**Issue by TroySigX** [glepnir/dashboard-nvim#320]
**Describe the bug**
I have some plugins that are lazy-loaded, meaning that by the time I enter the neovim buffer, those plugins are not loaded. However, instead of showing the number of actually loaded packages, dashboard just shows the number that are on my machine

**To Reproduce**
1. enable `packages` param in dashboard config file
2. open nvim and see dashboard

**Expected behavior**
Dashboard shows number of loaded packages, not total number of packages on local machine.

**Screenshots**
![image](https://user-images.githubusercontent.com/88051085/222239878-15b5ca06-d39d-4bac-9bcd-2de7a869d693.png)
![image](https://user-images.githubusercontent.com/88051085/222239923-4a96dcaf-a287-4cc7-ade6-6016918a2ba8.png)

**Comment by glepnir** [comment]
you can custom it to total or something you like
