### ISSUE TITLE
Have an empty center for doom theme

### ISSUE THREAD

**Issue by AlphabetsAlphabets** [glepnir/dashboard-nvim#328]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to have an empty center when `theme = 'doom'`.

**Describe the solution you'd like**
There should be an option such as `empty = true`, that will allow an empty center.

**Describe alternatives you've considered**
I had this in my config. 
```lua
                  center = {
                      {
                          icon = ' ',
                      },
                  },

```

So, the bare minimum is that `desc` must be set. `desc` must be text.

**Additional context**
Image the screenshot, but at the words "EMPTY", it is actually just empty. I only want the header and footer only. No center.
![image](https://user-images.githubusercontent.com/44822875/223643526-2f4feae7-d1db-46f5-bf8b-eee2a48d011c.png)

**Comment by glepnir** [comment]
I will fix it tomorrow

**Comment by AlphabetsAlphabets** [comment]
> I will fix it tomorrow

Thank you. I'll try and see if I can come up with a PR, if I can then I'll submit a PR. Been having fun with contributing to plugins I use.

**Comment by AlphabetsAlphabets** [comment]
@glepnir I made a PR that solves the issue: https://github.com/glepnir/dashboard-nvim/pull/329
