### ISSUE TITLE
Use split size to scale the dashboard instead of the window size

### ISSUE THREAD

**Issue by danielfalbo** [glepnir/dashboard-nvim#33]
How hard would it be to scale the dashboard based on the split size instead of the whole terminal window size? For example, right now this is what happens when I try to open the dashboard in two different vertical splits: 
![Screenshot 2020-11-17 at 13 46 32](https://user-images.githubusercontent.com/39460524/99392122-7fae2480-28db-11eb-81b0-e1a1ff0d2d37.png).
I'm not sure but I think this happens because it's trying to adapt to the size of the terminal, not to the size of its current vim split.
Would also be great to automatically adjust to window or split resize. In my .vimrc I have `autocmd VimResized * wincmd =`, this automatically balances the splits when I resize the terminal window, the dashboard may be refreshed in this scenario and also in the "split changed size" scenario (I think there's already an autocmd event option for that).

Thank you for this amazing dashboard plugin by the way :)

**Comment by glepnir** [comment]
hmm..This is neovim start-of-the-fold plugin. I don't know why  need to open the dashboard in vsplit buffer. The dashboard and startify use the same centering design,

**Comment by danielfalbo** [comment]
That's right, it would be pretty useless, thank you! I'm closing this 👍
