### ISSUE TITLE
Error after import: no such option: 'stc'

### ISSUE THREAD

**Issue by Xess1407** [glepnir/dashboard-nvim#331]
**Describe the bug**
Getting an error after importing the repo

**To Reproduce**
1. Put in packer: use "glepnir/dashboard-nvim"
2. Reload for :PackerSync
3. Reload and get the error

**Expected behavior**
No error, I suppose.

**Screenshots**
Error detected while processing UIEnter Autocommands for "*":
Error executing lua callback: vim/_meta.lua:0: no such option: 'stc'
stack traceback:
        [C]: in function 'nvim_get_option_info'
        vim/_meta.lua: in function '__index'
        vim/_meta.lua: in function ''
        vim/_meta.lua: in function '__newindex'
        .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:85: in function 'buf_local'
        .../pack/packer/start/dashboard-nvim/lua/dashboard/init.lua:266: in function 'instance'
        ...te/pack/packer/start/dashboard-nvim/plugin/dashboard.lua:12: in function <...te/pack/packer/start/dashboard-nvim/plugin/dashboard.lua:10>

**Comment by glepnir** [comment]
update your neovim
