### ISSUE TITLE
Errors on empty center/footer sections

### ISSUE THREAD

**Issue by Astrantia** [glepnir/dashboard-nvim#332]
**Describe the bug**
I only use the banner art for dashboard, and have no need for menu navigation

**To Reproduce**
Setup ur config like
```lua
local db = require("dashboard")
db.setup({
    theme = 'doom',
    config = {
        header = {
            [[]],
            [[]],
            [[]],
            [[]],
            [[]],
            " SOME ASCII ART",
            version_lines[2],
        },
        center = {
            {
                icon = '',
                icon_hl = 'group',
                desc = '',
                desc_hl = 'group',
                key = 'c',
                key_hl = 'group',
                action = '',
            },
        },
        footer = {}
    }
})
```
**Expected behavior**
No errors

The error is:
```
Error detected while processing UIEnter Autocommands for "*":
Error executing lua callback: ...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:111: attempt to perform arithmetic on local 'col' (a nil value)
stack traceback:
	...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:111: in function 'generate_center'
	...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:167: in function <...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:165>
	...al/share/nvim/lazy/dashboard-nvim/lua/dashboard/init.lua:214: in function 'load_theme'
	...al/share/nvim/lazy/dashboard-nvim/lua/dashboard/init.lua:268: in function 'instance'
	...ocal/share/nvim/lazy/dashboard-nvim/plugin/dashboard.lua:12: in function <...ocal/share/nvim/lazy/dashboard-nvim/plugin/dashboard.lua:10>
```

Some if checks for the arithmetics would make it not error. I understand that many people don't use dashboard like me however.

**Comment by glepnir** [comment]
the latest version of dashboard?

**Comment by Astrantia** [comment]
> the latest version of dashboard?

yup. this has been a problem since the big rewrite. with v1 it wasn't a problem

**Comment by glepnir** [comment]
this should work

```lua
 require("dashboard").setup {
        theme = 'doom',
        config = {
          header = opts.header,
          footer = { opts.footer },
          center = {
            {
              desc = '',
            },
          },
        }
      }
```

**Comment by Astrantia** [comment]
> 

That errors for me with the same error:

```
Error detected while processing UIEnter Autocommands for "*":
Error executing lua callback: ...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:111: attempt to perform arithmetic on local 'col' (a nil value)
stack traceback:
	...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:111: in function 'generate_center'
	...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:167: in function <...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:165>
	...al/share/nvim/lazy/dashboard-nvim/lua/dashboard/init.lua:214: in function 'load_theme'
	...al/share/nvim/lazy/dashboard-nvim/lua/dashboard/init.lua:268: in function 'instance'
	...ocal/share/nvim/lazy/dashboard-nvim/plugin/dashboard.lua:12: in function <...ocal/share/nvim/lazy/dashboard-nvim/plugin/dashboard.lua:10>
```

**Comment by PaoGon** [comment]
> > 
> 
> That errors for me with the same error:
> 
> ```
> Error detected while processing UIEnter Autocommands for "*":
> Error executing lua callback: ...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:111: attempt to perform arithmetic on local 'col' (a nil value)
> stack traceback:
> 	...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:111: in function 'generate_center'
> 	...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:167: in function <...re/nvim/lazy/dashboard-nvim/lua/dashboard/theme/doom.lua:165>
> 	...al/share/nvim/lazy/dashboard-nvim/lua/dashboard/init.lua:214: in function 'load_theme'
> 	...al/share/nvim/lazy/dashboard-nvim/lua/dashboard/init.lua:268: in function 'instance'
> 	...ocal/share/nvim/lazy/dashboard-nvim/plugin/dashboard.lua:12: in function <...ocal/share/nvim/lazy/dashboard-nvim/plugin/dashboard.lua:10>
> ```

I am having the same issue, any update  about this?

**Comment by Manix80** [comment]
same problem here, after the last update, "footer" does not appear anymore (doom theme)
