### ISSUE TITLE
vim-plug can not show how many plugins neovim loaded

### ISSUE THREAD

**Issue by codebysandwich** [glepnir/dashboard-nvim#335]
**Describe the bug**
use vim-plug manage plugins, dashboard always show `neovim loaded 0 packages`, it works ok with older branch `remove-default-header`

**To Reproduce**
1. nvim start neovim dashboard

**Expected behavior**
show numbers of packages loaded by vim-plug

**Screenshots**
![image](https://user-images.githubusercontent.com/32191093/227791467-9c2298b6-baf7-4d48-8e80-4be2fc312517.png)

**Comment by glepnir** [comment]
builtin not support vim-plug. you need custom it.
