### ISSUE TITLE
Unexpected vertical lines on displaying the dashboard

### ISSUE THREAD

**Issue by ansidev** [glepnir/dashboard-nvim#337]
**Describe the bug**

See the screenshot.

**To Reproduce**

1. Open a file in `nvim`.
2. Run command `:Dashboard` to open the dashboard
3. See error (vertical lines on the left side of the window)

**Expected behavior**

![Screenshot 2023-04-02 at 17 07 35](https://user-images.githubusercontent.com/6688235/229346471-9f0247f4-6443-4ed4-8c3e-f2de9acf145e.png)

**Screenshots**

![Screenshot 2023-04-02 at 16 53 39](https://user-images.githubusercontent.com/6688235/229346248-78d581db-ebce-446c-9373-4137bf416f30.png)

**Other Information**

```
NVIM v0.8.3 (with customized NvChad v2.0 setup)
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

**Comment by glepnir** [comment]
IDK what does nvchad do ? maybe some indent plugins ? problem not here i think
