### ISSUE TITLE
How to stop the dashboard from setting laststatus = 2 ?

### ISSUE THREAD

**Issue by danielfalbo** [glepnir/dashboard-nvim#34]
Hi! I do not use any status bar, how can I stop the dashboard from setting `laststatus` to `2` when leaving the dashboard buffer? I tried `autocmd FileType dashboard autocmd WinLeave <buffer> set laststatus=0` but does not work.

**Comment by glepnir** [comment]
@danielfalbo  use this
```vim
autocmd WinLeave <buffer> set showtabline=2
```

**Comment by danielfalbo** [comment]
Does not work :( This enables the tabline, I would like to stop the dashboard from enabling the status bar on the bottom. https://github.com/glepnir/dashboard-nvim/blob/26b7dd24cda20535510d9dd11bb3b5a4587d6f10/plugin/dashboard.vim#L34 For example commenting this line from the source code of the dashboard solves the problem. Is there a way to achieve this without changing the source code?

**Comment by glepnir** [comment]
@danielfalbo   ..my fault ..should be `autocmd WinLeave <buffer> set showtabline=0`

**Comment by danielfalbo** [comment]
That's not what I'm trying to achieve, I'm not trying to disable the *tabline*, I'm trying to disable the ordinary vim statusline, the one on the bottom (*laststatus*)! Maybe there's no solution without touching the source code.

I tried everything:
```
autocmd FileType dashboard autocmd WinLeave <buffer> set laststatus=0
autocmd FileType dashboard autocmd WinLeave <buffer> set showtabline=0
autocmd WinLeave <buffer> set laststatus=0
autocmd WinLeave <buffer> set showtabline=0
autocmd! FileType dashboard
augroup! dashboard
```
None of these works ): (and of course the ones that set showtabline to 0 were not even expected to work)

I think I'm gonna fork the dashboard and just comment out https://github.com/glepnir/dashboard-nvim/blob/26b7dd24cda20535510d9dd11bb3b5a4587d6f10/plugin/dashboard.vim#L34 👍   Thanks tough! Amazing plugin : )

**Comment by glepnir** [comment]
@danielfalbo  I will provide an option to disable this.

**Comment by glepnir** [comment]
try this `let g:dashboard_disable_statusline  = 1`

**Comment by danielfalbo** [comment]
Thank you much! Works beautifully : )
