### ISSUE TITLE
Opening files in neovim remote doesn't show lightline

### ISSUE THREAD

**Issue by niceloaf** [glepnir/dashboard-nvim#35]
Whenever I open a file in neovim remote lightline doesn't show up. It works fine in normal neovim though

**Comment by glepnir** [comment]
Don't know what happened ..dashboard works fine with spaceline.vim and galaxyline.nvim. but you can try this 
 `let g:dashboard_disable_statusline  = 1`

**Comment by niceloaf** [comment]
Well, I found a solution ```au! bufenter * set laststatus=2```
