### ISSUE TITLE
number and relativenumber sets are lost when opening a file after dashboard

### ISSUE THREAD

**Issue by s-zeng** [glepnir/dashboard-nvim#36]
When I use find file or new file, or otherwise start editing a file right after opening nvim into the dashboard, I no longer get line numbers on the left side. However, when I edit a file directly without opening the dashboard, I get line numbers. Expected behaviour: global line number setting is restored upon leaving the dashboard. What can be done to keep line numbers? Thanks in advance.

**Comment by glepnir** [comment]
I can't reproduce your problem with mininal config

```vim
set rtp+=~/workstation/vim/dashboard-nvim

set number
```

**Comment by ChristianChiarulli** [comment]
@s-zeng I don't wanna bump a closed issue, but how did you solve this? Was it some other plugins fault?

**Comment by ChristianChiarulli** [comment]
https://github.com/glepnir/dashboard-nvim/blob/563c8c1885044ad3fbb5339ad5a10439d9899e51/autoload/dashboard.vim#L40

^^ commenting out this for some reason fixed my issue

Then I just added a setlocal autocommand for `nonumber` when filetype is `dashboard`

Maybe It's conflicting with another plugin that sets macthpairs or something?

Also I have no idea why matchpairs controls whether or line numbers get reactivated. 🤷🏻‍♂️

**Comment by ChristianChiarulli** [comment]
nvm, this is just one of those things where then everything under that won't be counted

**Comment by ChristianChiarulli** [comment]
ok now, it seems like everything above was just completely random.

Somehow now my best guess is it depends on the size of the text relative to the terminal
