### ISSUE TITLE
win10 save/open session error 

### ISSUE THREAD

**Issue by coco-hkk** [glepnir/dashboard-nvim#42]
win10 error ouput:

```
处理  function sessions#session#session_save 时发生错误

无法打开并写入 “D:/Neovim/session/D:\Neovim\bin\.vim”

session `D:/Ndovim/session/D:\Neovim\bin\.vim` is now persistent
```
It seems to be caused by the variable `file_path`  in file `autoload/sessions/session.vim` .

> let file_path = g:session_directory.'/'.file_name.'.vim'

I try to reprocess `file_name` as follow, it looks working.

> let file_path = g:session_directory.'/'.split(file_name, '\')[-1].'.vim'

**Comment by glepnir** [comment]
这里路径符号是*nix.没判断win。。过会加一下。

**Comment by glepnir** [comment]
@coco-hkk  If this can work for you PR welcome. I don't have a win system to test it.
