### ISSUE TITLE
E15: Invalid expression: << trim END

### ISSUE THREAD

**Issue by DedSecer** [glepnir/dashboard-nvim#45]
I'm using neovim v0.4.4 and use dein.vim to install dashboard-nvim.
When I start neovim I will get output like this:
`Error detected while processing /home/ds/.config/nvim/dein/.cache/init.vim/.dein/autoload/dashboard/header.vim:
line  694:
E15: Invalid expression: << trim END`

**Comment by glepnir** [comment]
aha . found doom header work with only neovim 0.5

**Comment by glepnir** [comment]
now should be work.

**Comment by DedSecer** [comment]
Thanks,it worked now.
