### ISSUE TITLE
How to list session rather autoload latest session?

### ISSUE THREAD

**Issue by StevenChaoo** [glepnir/dashboard-nvim#55]
First of all, thanks for this amazing VIM plugin. It is a simple but crazy useful idea, that brings VIM way closer to being a full IDE.

My only request/question: is there a way to list sessions rather autoload latest session? If I open another file not in session list,  a error will return to me shows that can't load the session of this file.

Thanks a lot.

**Comment by glepnir** [comment]
maybe can implement in telescope .Because I am core member of telescope :)

**Comment by StevenChaoo** [comment]
:( so there is no way to select session manually?

**Comment by glepnir** [comment]
current just support reload latest session file. maybe you can use other session plugin and register it command to custom section

**Comment by StevenChaoo** [comment]
thanks~

**Comment by glepnir** [comment]
BTW you can use `:SessionLoad  |Tab` to select session

**Comment by mortezadadgar** [comment]
@glepnir any update on telescope support?

**Comment by LeonardMorgan** [comment]
I would love to see (multiple session + telescope) implemented that would be awesome.
