### ISSUE TITLE
Disable on startup?

### ISSUE THREAD

**Issue by AnatoleLucet** [glepnir/dashboard-nvim#56]
I have a bash alias to start nvim in "scratchpad mode" (using [Codi](https://github.com/metakirby5/codi.vim)).
I'd like my alias to disable dashboard-nvim on startup (with e.g. using something like Startify's `g:startify_disable_at_vimenter = 1`). Is it currently possible?

**Comment by glepnir** [comment]
`g:dashboard_disable_at_vimenter`

**Comment by AnatoleLucet** [comment]
Thanks! I think this could be worth adding to the readme.

**Comment by jdhao** [comment]
@glepnir  it seems that this option is removed. What is the latest way to dsiable dashboard at startup?

**Comment by glepnir** [comment]
`db.disable_at_vimente` type is bool

**Comment by jdhao** [comment]
It does not really work, my packer.nvim conf for dashboard:

```
    use { 'glepnir/dashboard-nvim', event = "VimEnter", config = [[require('config.dashboard-nvim')]] }
```

I have added the option in `~/.config/nvim/lua/config/dashboard-nvim.lua`:

```
local dashboard = require("dashboard")
dashboard.disable_at_vimenter = true
```

**Comment by glepnir** [comment]
did you update. there is no need to lazy load dashboard. it not increase your startup time.

**Comment by jdhao** [comment]
yeah, I did update to latest version of dashboard-nvim.

**Comment by glepnir** [comment]
not test.
