### ISSUE TITLE
How was the colored tiger made? 

### ISSUE THREAD

**Issue by sp1n0r** [glepnir/dashboard-nvim#57]
That header looks great. But I don't know how the multiple colors were achieved. 
https://user-images.githubusercontent.com/41671631/100820859-2113a980-348a-11eb-8a11-c1fa3a76ab2f.png

**Comment by glepnir** [comment]
use pipline `lolcat`

**Comment by sp1n0r** [comment]
Could you give an example?

**Comment by glepnir** [comment]
check my config glepnir/nvim
