### ISSUE TITLE
Make the header to vertical center.

### ISSUE THREAD

**Issue by singlexyz** [glepnir/dashboard-nvim#59]
<img width="1392" alt="截屏2021-03-09 上午5 33 00" src="https://user-images.githubusercontent.com/4456413/110384703-f8a6d700-8098-11eb-97ed-b3ceab165d94.png">

I remove the sessions and footer, so make the dashboard just for watch. 

```
let g:dashboard_custom_footer = []
let g:dashboard_custom_section = {}
```

It's possible to make the header position to vertical center, then make the cursor invisible.

**Comment by glepnir** [comment]
no. vim can't control the cursor. because the vim like a cli in terminal so it just use terminal intreface.
