### ISSUE TITLE
Removes line numbers after opening

### ISSUE THREAD

**Issue by ChristianChiarulli** [glepnir/dashboard-nvim#63]
It seems the line numbers are removed after opening (as well as other settings) depending on the text size relative to the terminal size. 

numbers not working with fontsize 11
![image](https://user-images.githubusercontent.com/29136904/112052400-76eb8a80-8b29-11eb-9646-346b60398b14.png)

numbers working with fontsize 10
![image](https://user-images.githubusercontent.com/29136904/112052559-a4383880-8b29-11eb-9470-fc0e4ff2ddc8.png)

This is relative to you terminal window so it takes some adjusting.

The above pictures are in alacritty, I have also tested on iterm2

**Comment by glepnir** [comment]
strange question. why it's relate the temrinal text size.. which config did you test? I can't reproduce it.

**Comment by ahmedkhalf** [comment]
OH, I have the same issue! maybe this can provide more details: #65

**Comment by ChristianChiarulli** [comment]
@ahmedkhalf 

So how I "fixed" it is by forking and removing `nobuflisted` from the autocommand in autoload/dashboard.vim.

That seemed to stop persisting the options set by the autocommand. No idea why.

**Comment by ronisbr** [comment]
I also have the same problem here. It happens on iTerm2 and on Alacritty.
