### ISSUE TITLE
Invalid expression: getbufinfo(w:dashboard_preview_bufnr)[0]

### ISSUE THREAD

**Issue by davidvalaz** [glepnir/dashboard-nvim#66]
Seems like the latest commit has broken the ability to load the dashboard using the `:Dashboard` command:

<img width="788" alt="Screen Shot 2021-03-27 at 00 18 44@2x" src="https://user-images.githubusercontent.com/80173369/112704331-24e09700-8e92-11eb-9e0a-f840341d1e22.png">

If I rollback two commits ago, it works just fine.

**Comment by davidvalaz** [comment]
Hi @glepnir, I notice we're still getting this error when we specify a custom preview header and try to use `:Dashboard`.

For reference:
```lua
vim.g.dashboard_preview_command = 'cat'
vim.g.dashboard_preview_pipeline = 'lolcat'
vim.g.dashboard_preview_file = home .. '/.config/nvim/static/neovim.cat'
vim.g.dashboard_preview_file_height = 10
vim.g.dashboard_preview_file_width = 80
```

If I use the default header then `:Dashboard` works as expected.

Checking my Neovim health, everything is green:
```
INFO: Platform: macos
INFO: Nvim: NVIM v0.5.0-dev+1178-gf0ace6d41
```

**Comment by glepnir** [comment]
please provide the reproduce step.

**Comment by davidvalaz** [comment]
Okay this is interesting...it seems to be weird when I restore a session:

Full dashboard config:
```lua
function M.dashboard()
    local home = os.getenv('HOME')
    
    g.dashboard_default_executive = 'telescope'
    g.dashboard_session_directory = session_path

    vim.g.dashboard_preview_command = 'cat'
    vim.g.dashboard_preview_pipeline = 'lolcat'
    vim.g.dashboard_preview_file = home .. '/.config/nvim/static/neovim.cat'
    vim.g.dashboard_preview_file_height = 10
    vim.g.dashboard_preview_file_width = 80

    g.dashboard_custom_section = {
        a = {
            description = {'  Load Last Session    '},
            command = 'Prosession .'
        },
        b = {
            description = {'  Recently Opened Files'},
            command = 'Telescope oldfiles'
        },
        c = {
            description = {'  Find File            '},
            command = 'Telescope find_files find_command=rg,--hidden,--files'
        },
        e = {
            description = {'  Find Word            '},
            command = 'Telescope live_grep'
        },
        f = {
            description = {'  Marks                '},
            command = 'Telescope marks'
        }
    }
    g.dashboard_footer_icon = '🐈 '

    cmd ':ab db Dashboard'
end
```

Reproduction steps:
1) Load a previous session from Dashboard
2) Enter `:Dashboard`
3) Observe the error

![Screen Shot 2021-03-28 at 09 20 48](https://user-images.githubusercontent.com/80173369/112746515-2485f000-8fa7-11eb-9c12-b14b2736a2a8.gif)

If I just load a file and go back to the Dashboard, it works just fine.

**Comment by glepnir** [comment]
reproduce with session... If don't load from session that works fine.

**Comment by glepnir** [comment]
reproduce with session... If don't load from session that works fine.

**Comment by davidvalaz** [comment]
The thing I don't understand is when I disable the ` vim.g.dashboard_preview` options, it works fine:

![Screen Shot 2021-03-28 at 10 05 39](https://user-images.githubusercontent.com/80173369/112747413-379bbe80-8fad-11eb-8925-866cf945adaf.gif)

I tried recreating a session and I still get the same error. Weird.

**Comment by glepnir** [comment]
fixed.
