### ISSUE TITLE
Sessions don't work

### ISSUE THREAD

**Issue by jin-ahn** [glepnir/dashboard-nvim#67]
I run SessionSave can get confirmation that 'is now persistent'. However when I try to load it will say the session loaded, but it will just be a blank page

**Comment by glepnir** [comment]
hmm can you provide a reproduce step?

**Comment by rajprakharpatel** [comment]
I am having a similar problem where I get the confirmation that "{path} is now persistent", but on trying to load it shows error as 'The  session "{path}.vim" doesn't exist.
While I have checked manually that the file is there on the path mentioned and I can source is correctly using ":source [path]" command

**Comment by rajprakharpatel** [comment]
> I am having a similar problem where I get the confirmation that
> 
> > "{path} is now persistent"
> 
> But on trying to load it shows error as
> 
> > 'The  session "{path}.vim" doesn't exist.
> 
> While I have checked manually that the file is there on the path mentioned and I can source is correctly using ":source [path]" command

My bad I was using '~' in the path string for sessions which was causing the problem(it was taking the path relative to the cwd). After changing it to this it's working
`vim.g.dashboard_session_directory = vim.fn.stdpath('cache').."/session"`
