### ISSUE TITLE
打开vim时报错

### ISSUE THREAD

**Issue by FlyingMcDonald** [glepnir/dashboard-nvim#68]
最近一段时间，当我打开vim的时候会出现这样的error

![2021-04-09_14-30](https://user-images.githubusercontent.com/40425574/114139231-4dd74200-98fe-11eb-902f-dbc026d644b5.png)

我尝试进行定位后发现可能是这行代码引发的问题
```vimscript
call luaeval("require('dashboard.preview').open_preview")()
```
代码的位置在`autoload/dashboard.vim`

请问我该如何解决这个问题

**Comment by glepnir** [comment]
only support neovim 0.5+
