### ISSUE TITLE
Error detected while processing function <SNR>29_loaded_dashboard[3]..dashboard#instance[73] 

### ISSUE THREAD

**Issue by siduck76** [glepnir/dashboard-nvim#69]
I have installed the plugin with packer , didnt add any configuration and I get these errors on startup :

![image](https://user-images.githubusercontent.com/59060246/114277627-8899c100-9a49-11eb-8298-16881847f6f4.png)

**Comment by glepnir** [comment]
hmm. did you test the min config? i can't reproduce it.

**Comment by siduck76** [comment]
min config? Do you mean this : https://github.com/glepnir/dashboard-nvim#minimal-vimrc ? I just have dashboard-nvim installed and telescope plugin installed. Didnt add any config so far .

**Comment by glepnir** [comment]
try to update neovim version.

**Comment by siduck76** [comment]
I did but still same error :(

**Comment by siduck76** [comment]
@glepnir :PackerCompile fixed it .
