### ISSUE TITLE
Session Load/Save Hooks

### ISSUE THREAD

**Issue by cenk1cenk2** [glepnir/dashboard-nvim#72]
Greetings @glepnir,

Thank you for work on this amazing plugin. It modernizes the neovim setup quite much. Is it possible to embed in session load/save's like pre and post commands?

I want to close out empty buffers whenever I open a session because I sometimes have leftover directory buffer or some random empty buffers on the session. Is this something possible or am I missing something that is already implemented in?

**Comment by glepnir** [comment]
yup can support it.

**Comment by obj-obj** [comment]
> Greetings @glepnir,
> 
> Thank you for work on this amazing plugin. It modernizes the neovim setup quite much. Is it possible to embed in session load/save's like pre and post commands?
> 
> I want to close out empty buffers whenever I open a session because I sometimes have leftover directory buffer or some random empty buffers on the session. Is this something possible or am I missing something that is already implemented in?

`set sessionoptions-=blank` will prevent blank buffers from being saved in sessions

**Comment by cenk1cenk2** [comment]
You are back, cool! There were some messages including you and the hospital so hope you are doing fine!

**Comment by glepnir** [comment]
Thanks ,Looks good so far, the surgery was a success, but I'm still on medication for a long time
