### ISSUE TITLE
Add an example of mapping commands with Lua?

### ISSUE THREAD

**Issue by ajstrand** [glepnir/dashboard-nvim#73]
I’m new to using neovim/vim and I wanted to try this plugin. 

I tried translating the mappings for the built in functionality of the dashboard to lua, but I couldn’t get my mappings to work.

could you create an example of how to map the default commands of the dashboard using Lua? 

For more context, I’m using telescope with this dashboard plugin.

**Comment by arpangreat** [comment]
Yes , you can write the mapping like this :

```lua

-- DashBoard 
vim.api.nvim_set_keymap('n','<Leader>fh',':DashboardFindHistory<CR>', { noremap = true , silent = false })
vim.api.nvim_set_keymap('n','<Leader>sl',':<C-u>SessionLoad<CR>', { noremap = true , silent = false })
vim.api.nvim_set_keymap('n','<Leader>fa',':DashboardFindWord<CR>', { noremap = true , silent = false })
vim.api.nvim_set_keymap('n','<Leader>fb',':DashboardJumpMark<CR>', { noremap = true , silent = false })
```

For customization , you can change the second parameter or starting with `<Leader>*` as you want , cause it is your trigger for the mapping 

Visit :
https://arpangreat.github.io/post/portingviminlua/

For more information about writing neovim config lua , made by me 😊

**Comment by ajstrand** [comment]
@arpangreat thank you so much fo your answer! I must have been using the `nvim_set_keymap` API  incorrectly, but testing the mappings you provided work as expected.

**Comment by arpangreat** [comment]
No problem man ❤️ loved to help you 😊
