### ISSUE TITLE
Tabs don't get loaded when I restore a session

### ISSUE THREAD

**Issue by rebuilt** [glepnir/dashboard-nvim#76]
Hello.  Thank you for your plugin.

I'm using the [LunarVim](https://github.com/ChristianChiarulli/LunarVim) configuration of neovim.  It includes dashboard and [barbar](https://github.com/romgrk/barbar.nvim).  Barbar provides tabs for file navigation.  I've noticed that when I load a session the tabs do not show up correctly.  This only occurs when loading a session from the Dashboard home screen.  If I open up neovim with a new buffer and load a saved session, tabs work as expected.  I'm not sure what's different about the home screen vs any other buffer.  

My workaround is to 

```bash
nvim i  #  The file name can be anything since it never gets saved and will be lost immediately when loading a session
```
Once I've opened neovim without the dashboard home screen, tabs appear correctly in a loaded session.

**Comment by Clejd** [comment]
Try this: autocmd BufLeave <buffer> set showtabline=2 (I changed "WinLeave" with "BufLeave" and worked for me)

**Comment by Clejd** [comment]
Try this:
`autocmd BufLeave set showtabline=2 `
(I changed "WinLeave" with "BufLeave" and worked for me)
