### ISSUE TITLE
dashboard_preview_file not cleared with e.g. DashboardNewFile

### ISSUE THREAD

**Issue by mrusme** [glepnir/dashboard-nvim#79]
I'm using `let g:dashboard_preview_file = '~/.config/nvim/motd'`, which is a file that contains shell control chars. When I run the `DashboardNewFile` command, the contents from the dashboard_preview_file are still being displayed and not cleared off the screen. The writing in i mode then happens "behind" the contents.

**Comment by wael444** [comment]
any fixes?

**Comment by mrusme** [comment]
This bug really makes dashboard-nvim kind of useless, since the editor can't be used once the dashboard was visible. :-(

**Comment by glepnir** [comment]
I will check it later .sorry for this

**Comment by mrusme** [comment]
Unfortunately this hasn't been resolved. The header still does not disappear when a new file is loaded from the dashboard.

**Comment by glepnir** [comment]
@mrusme  please provide your step that can reproduce

**Comment by mrusme** [comment]
@glepnir check [my config here](https://github.com/mrusme/dotfiles/blob/e41f802c91922d7ab3bf0c7af47b9f974f496cd2/nvim/init.vim#L823).

**Comment by glepnir** [comment]
@mrusme   fixed

**Comment by mrusme** [comment]
Confirmed it works now! Thank you!
