### ISSUE TITLE
Disabling a few options in the dashboard

### ISSUE THREAD

**Issue by YJH16120** [glepnir/dashboard-nvim#80]
These are the defaults of dashboard, personally I don't use change_colorscheme, `book_marks`, etc.
```
eg : "SPC mean the leaderkey
let g:dashboard_custom_shortcut={
\ 'last_session'       : 'SPC s l',
\ 'find_history'       : 'SPC f h',
\ 'find_file'          : 'SPC f f',
\ 'new_file'           : 'SPC c n',
\ 'change_colorscheme' : 'SPC t c',
\ 'find_word'          : 'SPC f a',
\ 'book_marks'         : 'SPC f b',
\ }
```
When I only include the ones that I use, dashboard gives an error. For example if I remove the `change_colorscheme` line, it gives an error saying `Key not present in Dictionary: "change_colorscheme"`

Is there a way for me to not include everything?

**Comment by YJH16120** [comment]
I just didn't read the documentation properly smh

**Comment by syberant** [comment]
For anybody stumbling on this issue like me, `g:dashboard_custom_section` is *in place of* the default session instead of *in addition to* which I wrongly assumed it was.
