### ISSUE TITLE
The logo in preview file not loaded when using the demo config

### ISSUE THREAD

**Issue by knightz1224** [glepnir/dashboard-nvim#84]
![Screenshot_20210619-112006.png](https://user-images.githubusercontent.com/5117206/122629535-53b48500-d0f0-11eb-82cd-037330ff411c.png)
![Screenshot_20210619-112044.png](https://user-images.githubusercontent.com/5117206/122629568-83fc2380-d0f0-11eb-9226-bfd81c5e1c7a.png)

**Comment by knightz1224** [comment]
OS: Debian GNU/Linux 11 (bullseye) x86_64
Neovim: 0.5.0

**Comment by knightz1224** [comment]
fixed by moving the config  block above.

**Comment by jltwheeler** [comment]
> fixed by moving the config block above.

I'm running into this same problem, could you please be more specific as to what 'block' you moved for it to render?

**Comment by nyngwang** [comment]
Hi, I have the same question.
