### ISSUE TITLE
Status line appears after focussing again of dashboard

### ISSUE THREAD

**Issue by ashishbinu** [glepnir/dashboard-nvim#87]
I have set `vim.g.dashboard_disable_statusline = 1` but when i open telescope and then exit telescope the statusline appears in dashboard.

https://user-images.githubusercontent.com/56691622/124385367-d04f8200-dcf2-11eb-81bc-bbcf7395e95b.mp4

Is there any autocmd to use to fix it

**Comment by kevinrambaud** [comment]
In addition to the setting `dashboard_disable_statusline` set to `1`, you could add the following autocmd to make sure the status line stays hidden.

```VimL
autocmd BufEnter,BufWinEnter,WinEnter,CmdwinEnter * if &filetype == "dashboard" | set laststatus=0 | else | set laststatus=2 | endif
```
