### ISSUE TITLE
scrolloff

### ISSUE THREAD

**Issue by sbeckeriv** [glepnir/dashboard-nvim#95]
Dearest Maintainer,

Thanks for the nice dashboard!  I use scrolloff=9999 to keep my scroll centered. i am trying `autocmd FileType dashboard set scrolloff=0` but it does not seem to work. Any ideas?

Thanks again!
Becker

**Comment by OdilonDamasceno** [comment]
Try `autocmd FileType dashboard set mouse=`

**Comment by sbeckeriv** [comment]
thanks for the suggestion, however, it did not work for me.

**Comment by daephx** [comment]
For me `set scrolloff=999` had an issue with scrolling causing the dashboard to jump up and down.

I played around with the suggesting to disable the mouse completely, but It persisted even after closing the dashboard to open another file. So I tried to set another autocmd to reenable it when leaving the dashboard.

Added to `augroup dashboard_au`:
```vim
" Set to really high value - prevents Page Up/Down
autocmd User dashboardReady setlocal scrolloff=999
" Reset when leaving dashboard
autocmd FileType dashboard autocmd BufLeave <buffer> setlocal scrolloff=0

" Disable the mouse - prevents mousewheel
autocmd User dashboardReady setlocal mouse=
" Reset when leaving dashboard
autocmd FileType dashboard autocmd BufLeave <buffer> set mouse=a
```
This doesn't seem all that clean but it's something.
